"""Tests for platterpus.parsers.eac_log.

Golden test against the committed EAC baseline (output_reference/EAC_flac/),
plus format-sniffing (which program's EAC-layout log this is) and
degrade-to-empty behaviour.
"""

from __future__ import annotations

from pathlib import Path

from platterpus import eac_log_export
from platterpus.parity import decode_log_bytes
from platterpus.parsers.eac_log import (
    PLATTERPUS_EAC_BANNERS,
    eac_log_producer,
    looks_like_eac_log,
    parse_eac_copy_crcs,
)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_EAC_BASELINE = (
    _REPO_ROOT / "output_reference" / "EAC_flac" / "eac_baseline_police_classics.log"
)
#: A real EAC-compatible log written by Platterpus 0.6.4b3 (2026-08-04), so it
#: carries the OLD first line. Users hold files like it; it is never rewritten.
_OLD_BANNER_EXPORT = (
    _REPO_ROOT
    / "output_reference"
    / "cyanrip_fork_flac"
    / "cyanrip_fork_police_classics_EACcompatible.log"
)
#: The two first lines, as literals, so the tests do not read them off the table
#: they are checking.
_NEW_BANNER = "Platterpus rip log in EAC's layout, not produced by Exact Audio Copy"
_OLD_BANNER = "Exact Audio Copy-compatible log generated by Platterpus"


def _baseline_text() -> str:
    # The committed EAC logs are stored in their native UTF-16 (as EAC writes
    # them); decode through the same path the parity tool/CLI uses.
    return decode_log_bytes(_EAC_BASELINE.read_bytes())


# Ground truth read off the committed EAC baseline — the bit-perfect reference.
_EXPECTED_CRCS = {
    1: "B0D122E7",
    2: "985AAE32",
    3: "59D352DD",
    4: "60D796AE",
    5: "E0036697",
    6: "B32769D6",
    7: "CCBFF669",
    8: "D723C1B0",
    9: "6F6E4A5F",
    10: "3A33519F",
    11: "56BFC63D",
    12: "D78CEAEF",
    13: "DA6A4DAF",
    14: "787BA2D6",
}


def test_parses_the_committed_eac_baseline() -> None:
    assert parse_eac_copy_crcs(_baseline_text()) == _EXPECTED_CRCS


def test_looks_like_eac_log_true_for_the_baseline() -> None:
    assert looks_like_eac_log(_baseline_text()) is True


def test_looks_like_eac_log_false_for_other_formats() -> None:
    # The legacy log format's real header line, then a cyanrip banner.
    for other in ("Log created by: whipper 0.10.0\n", "cyanrip 0.9.3.1 (abc)\n", ""):
        assert looks_like_eac_log(other) is False
        assert eac_log_producer(other) is None


# --- Which program's EAC-layout log is this? (handshake R28.L7 S28-S32) -------
#
# Our export's first line began "Exact Audio Copy-compatible…" until 0.6.62, and
# `^Exact Audio Copy\b` filed it as EAC's own log. The fork accepted moving those
# words off the start of line 1 (their round 29 lap 1 S31). The parser has to know
# three first lines: EAC's, our new one, and our old one, which users still hold.


def test_a_genuine_eac_log_is_named_as_eacs() -> None:
    """The real EAC 1.8 baseline, decoded from its native UTF-16 with its BOM."""
    text = _baseline_text()
    assert text.lstrip("\ufeff").startswith("Exact Audio Copy V1.8"), (
        "sanity: the committed baseline must open with EAC's own banner"
    )
    assert eac_log_producer(text) == "exact_audio_copy"
    assert looks_like_eac_log(text) is True


def test_our_new_first_line_is_recognised_as_ours() -> None:
    text = (
        f"{_NEW_BANNER}\n"
        "  Rendered from a rip by cyanrip 0.9.4.\n"
        "\n"
        "Track  1\n"
        "     Copy CRC B0D122E7\n"
    )
    assert eac_log_producer(text) == "platterpus"
    assert looks_like_eac_log(text) is True
    assert parse_eac_copy_crcs(text) == {1: "B0D122E7"}


def test_an_old_banner_export_is_still_ours_and_not_eacs() -> None:
    """A real file written by Platterpus 0.6.4b3, with the old first line.

    It begins "Exact Audio Copy", so the loose EAC banner regex alone would call it
    EAC's own log, which is the misfiling the handshake item is about. It must be
    recognised as ours, and its Copy CRCs must still read.
    """
    text = _OLD_BANNER_EXPORT.read_text(encoding="utf-8")
    assert text.splitlines()[0] == _OLD_BANNER, (
        "sanity: this committed artifact must carry the OLD first line, or this test "
        "is not about old files"
    )
    assert eac_log_producer(text) == "platterpus"
    assert looks_like_eac_log(text) is True
    crcs = parse_eac_copy_crcs(text)
    assert len(crcs) == 14, f"the disc has 14 tracks; read {len(crcs)}"
    assert crcs[1] == "B0D122E7"


def test_the_producer_is_read_from_the_first_non_blank_line_only() -> None:
    # Leading blank lines, or a BOM in front of the banner, do not hide it.
    assert eac_log_producer(f"\n  \n{_NEW_BANNER}\n") == "platterpus"
    assert eac_log_producer(f"\ufeff{_NEW_BANNER}\n") == "platterpus"
    assert eac_log_producer(f"\ufeff{_OLD_BANNER}\n") == "platterpus"
    # Case does not turn our old banner into EAC's.
    assert eac_log_producer(_OLD_BANNER.upper() + "\n") == "platterpus"
    # A log that merely QUOTES a banner further down is not in EAC's layout.
    assert eac_log_producer(f"cyanrip 0.9.4 (x)\nSomeone said: {_NEW_BANNER}\n") is None
    assert eac_log_producer(f"cyanrip 0.9.4 (x)\n{_OLD_BANNER}\n") is None
    # Our name alone is not our banner.
    assert eac_log_producer("Platterpus 0.6.62\n") is None
    # EAC's banner without a version (a hand-trimmed baseline) is still EAC's.
    assert eac_log_producer("Exact Audio Copy\n     Copy CRC B0D122E7\n") == (
        "exact_audio_copy"
    )


def test_the_writers_first_line_is_the_newest_recognised_banner() -> None:
    """The writer and the reader answer one question, so they share one key.

    `eac_log_export._BANNER` writes the first line; `PLATTERPUS_EAC_BANNERS` is how
    the parser recognises it, newest first. A rewording of one without the other
    would make every new log "not an EAC-layout log" to our own tooling.
    """
    assert eac_log_export._BANNER == PLATTERPUS_EAC_BANNERS[0] == _NEW_BANNER
    assert _OLD_BANNER in PLATTERPUS_EAC_BANNERS
    assert not _NEW_BANNER.casefold().startswith("exact audio copy")


def test_parse_handles_minimal_block() -> None:
    log = "Exact Audio Copy V1.8\n\nTrack  1\n     Copy CRC ABCD1234\n"
    assert parse_eac_copy_crcs(log) == {1: "ABCD1234"}


def test_lowercase_crc_is_normalised_to_uppercase() -> None:
    log = "Track  7\n     Copy CRC abcd1234\n"
    assert parse_eac_copy_crcs(log) == {7: "ABCD1234"}


def test_copy_crc_without_a_track_header_is_ignored() -> None:
    # A Copy CRC line with no preceding "Track N" can't be attributed.
    assert parse_eac_copy_crcs("     Copy CRC ABCD1234\n") == {}


def test_garbage_yields_empty_mapping() -> None:
    assert parse_eac_copy_crcs("not a log at all\n:::\n") == {}
    assert parse_eac_copy_crcs("") == {}
