"""Tests for platterpus.eac_log_export (the unsigned, attributed EAC-layout log).

The renderer must be (1) honest — clearly attributed, never a fake EAC version
banner or signed checksum; and (2) useful — detected as EAC-format by our own
parser so the per-track Copy CRCs read straight back out for a parity diff.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

from platterpus.eac_log_export import render_eac_style_log
from platterpus.parity import track_copy_crcs
from platterpus.parsers.eac_log import looks_like_eac_log
from platterpus.parsers.rip_log import (
    AccurateRipResult,
    RipLog,
    RippingInfo,
    TrackResult,
)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_CYANRIP_REFERENCE = (
    _REPO_ROOT
    / "output_reference"
    / "cyanrip_flac"
    / "cyanrip_flac_police_classics.log"
)
_EAC_BASELINE = (
    _REPO_ROOT / "output_reference" / "EAC_flac" / "eac_baseline_police_classics.log"
)


def _sample_log() -> RipLog:
    return RipLog(
        log_creator="cyanrip 0.9.3",
        creation_date="2026-06-28",
        ripping_info=RippingInfo(
            drive="PIONEER BD-RW BDR-209D",
            defeat_audio_cache=True,
            read_offset_correction=667,
            overread_lead_out=False,
            gap_detection="Appended to previous track",
        ),
        tracks=(
            TrackResult(
                number=1,
                filename="01 - Roxanne.flac",
                peak_level=0.942,
                extraction_speed=1.6,
                extraction_quality=100.0,
                test_crc="b0d122e7",
                copy_crc="b0d122e7",
                status="ripped successfully",
                accuraterip_v2=AccurateRipResult(
                    version=2,
                    result="accurately ripped, confidence 200",
                    confidence=200,
                    local_crc="22B9924D",
                ),
            ),
            TrackResult(
                number=2,
                filename="02 - Message.flac",
                copy_crc="DEADBEEF",
                status="ripped successfully",
                accuraterip_v1=AccurateRipResult(
                    version=1, result="not found", confidence=None
                ),
            ),
        ),
        accuraterip_summary="13/14 tracks ripped accurately (AccurateRip)",
        health_status="No errors occurred",
    )


def test_first_line_attributes_to_platterpus_not_eac() -> None:
    text = render_eac_style_log(_sample_log())
    first = text.splitlines()[0]
    assert first.startswith("Exact Audio Copy-compatible log generated by Platterpus")
    # Unmistakable in a head/at-a-glance: it says NOT genuine somewhere up top.
    head = "\n".join(text.splitlines()[:6])
    assert "NOT a genuine EAC log" in head


def test_never_emits_a_fake_eac_checksum_signature() -> None:
    text = render_eac_style_log(_sample_log())
    # A real EAC log ends with "==== Log checksum <64 hex> ====". We must never
    # produce that — it is EAC's signature and forging it is the whole no-go.
    assert not re.search(r"==== Log checksum [0-9A-Fa-f]{64} ====", text)
    assert "NOT signed by Exact Audio Copy" in text


def test_roundtrips_through_our_parity_reader() -> None:
    # Detected as EAC-format AND the Copy CRCs read straight back out, so the
    # rendered log can be diffed/compared against a real EAC baseline.
    text = render_eac_style_log(_sample_log())
    assert looks_like_eac_log(text)
    assert track_copy_crcs(text) == {1: "B0D122E7", 2: "DEADBEEF"}


def test_accuraterip_line_uses_shared_confidence_rule() -> None:
    text = render_eac_style_log(_sample_log())
    # Track 1: a real confidence-200 match -> "Accurately ripped".
    assert "Accurately ripped (confidence 200)" in text
    assert "[22B9924D]" in text and "(AR v2)" in text
    # Track 2: confidence None -> NOT claimed as verified.
    assert "Track not present in AccurateRip database" in text


def test_renders_read_settings_block() -> None:
    text = render_eac_style_log(_sample_log())
    assert "Read offset correction" in text and "667" in text
    assert "Defeat audio cache      : Yes" in text
    assert "PIONEER BD-RW BDR-209D" in text


def test_records_software_provenance_when_supplied() -> None:
    """Platterpus version+build and the FLAC/derived encoder versions appear in
    the attribution header when passed — the archival provenance fix — while the
    honesty guardrails (no fake EAC banner, no checksum, NOT-signed footer) hold.
    """
    text = render_eac_style_log(
        _sample_log(),
        platterpus_version="0.4.18",
        build_fingerprint="abc1234",
        encoder_versions={"flac": "1.5.0", "metaflac": "1.5.0", "ffmpeg": "8.1.1"},
    )
    assert "Generated by Platterpus 0.4.18 (build abc1234)." in text
    assert "FLAC encoder: flac 1.5.0, metaflac 1.5.0." in text
    assert "Derived-format encoder: ffmpeg 8.1.1." in text
    # cyanrip source line is still the genuine parsed one, not forged.
    assert "Rendered from a rip by cyanrip 0.9.3." in text
    # Honesty guardrails unchanged.
    assert "NOT signed by Exact Audio Copy" in text
    assert not re.search(r"Exact Audio Copy V\d", text)  # no fake version banner
    assert not re.search(r"==== Log checksum [0-9A-Fa-f]{64} ====", text)


def test_omits_provenance_lines_when_not_supplied() -> None:
    """Absent values are omitted, never invented (the honesty gate). ffmpeg is
    left out for a FLAC-only rip (no derived-format encoder ran)."""
    # Nothing supplied → none of the new lines appear (back-compat with callers
    # that don't pass provenance).
    bare = render_eac_style_log(_sample_log())
    assert "Generated by Platterpus" not in bare
    assert "FLAC encoder:" not in bare
    assert "Derived-format encoder" not in bare
    # FLAC-only: flac/metaflac present, ffmpeg omitted because it wasn't supplied.
    flac_only = render_eac_style_log(
        _sample_log(),
        platterpus_version="0.4.18",
        encoder_versions={"flac": "1.5.0", "metaflac": "1.5.0"},
    )
    assert "FLAC encoder: flac 1.5.0, metaflac 1.5.0." in flac_only
    assert "Derived-format encoder" not in flac_only
    # No build fingerprint supplied → the "(build …)" suffix is dropped.
    assert "Generated by Platterpus 0.4.18." in flac_only


def test_never_raises_with_provenance_on_partial_log() -> None:
    """The never-raises contract holds even with provenance kwargs on an empty
    RipLog."""
    text = render_eac_style_log(
        RipLog(),
        platterpus_version="0.4.18",
        build_fingerprint="abc1234",
        encoder_versions={"flac": "1.5.0"},
    )
    assert text.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "NOT signed by Exact Audio Copy" in text


def test_does_not_fabricate_read_mode_or_c2_pointers() -> None:
    """Regression (#32): RippingInfo has no field for EAC's "Read mode" or "Make
    use of C2 pointers", and cyanrip doesn't report them — so the export must not
    hardcode "Secure"/"No". Inventing rip facts would violate the same
    never-invent-a-log-line rule the banner states."""
    text = render_eac_style_log(_sample_log())
    assert "Read mode" not in text
    assert "C2 pointers" not in text
    assert "Secure" not in text


def test_never_raises_on_empty_or_partial_log() -> None:
    # An empty RipLog still yields a valid, attributed, unsigned log.
    text = render_eac_style_log(RipLog())
    assert text.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "NOT signed by Exact Audio Copy" in text
    # A partial track (Nones everywhere) must not crash the formatter.
    partial = RipLog(tracks=(TrackResult(number=1),))
    out = render_eac_style_log(partial)
    assert "Track  1" in out
    assert "Track not present in AccurateRip database" in out


# --- CLI: scripts/render_eac_log.py ---------------------------------------


def _load_cli():
    spec = importlib.util.spec_from_file_location(
        "render_eac_log_cli", _REPO_ROOT / "scripts" / "render_eac_log.py"
    )
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_cli_renders_committed_cyanrip_log(capsys) -> None:
    cli = _load_cli()
    rc = cli.main([str(_CYANRIP_REFERENCE)])
    out = capsys.readouterr().out
    assert rc == 0
    assert out.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "B0D122E7" in out  # track 1 Copy CRC carried through
    assert "NOT signed by Exact Audio Copy" in out


def test_cli_writes_output_file(tmp_path: Path, capsys) -> None:
    cli = _load_cli()
    dest = tmp_path / "rendered.log"
    rc = cli.main([str(_CYANRIP_REFERENCE), "-o", str(dest)])
    assert rc == 0
    written = dest.read_text(encoding="utf-8")
    assert looks_like_eac_log(written)
    assert track_copy_crcs(written)[1] == "B0D122E7"


def test_cli_refuses_a_real_eac_log(capsys) -> None:
    # Rendering an EAC log into "EAC style" is meaningless — and we won't
    # round-trip a real EAC log into our attributed format. Exit non-zero.
    cli = _load_cli()
    rc = cli.main([str(_EAC_BASELINE)])
    assert rc == 2
    assert "already looks like an EAC log" in capsys.readouterr().err


def test_cli_missing_file_returns_2(tmp_path: Path) -> None:
    cli = _load_cli()
    assert cli.main([str(tmp_path / "nope.log")]) == 2
