"""Tests for platterpus.eac_log_export (the unsigned, attributed EAC-layout log).

The renderer must be (1) honest — clearly attributed, never a fake EAC version
banner or signed checksum; and (2) useful — detected as EAC-format by our own
parser so the per-track Copy CRCs read straight back out for a parity diff.
"""

from __future__ import annotations

import hashlib
import importlib.util
import re
from dataclasses import replace
from pathlib import Path

from platterpus.eac_log_export import (
    _UNREPORTED,
    render_eac_style_log,
    verify_eac_style_log_checksum,
)
from platterpus.parity import track_copy_crcs
from platterpus.parsers.eac_log import looks_like_eac_log
from platterpus.parsers.rip_log import (
    AccurateRipResult,
    RipLog,
    RippingInfo,
    TrackResult,
)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_CYANRIP_REFERENCE = (
    _REPO_ROOT
    / "output_reference"
    / "cyanrip_flac"
    / "cyanrip_flac_police_classics.log"
)
_EAC_BASELINE = (
    _REPO_ROOT / "output_reference" / "EAC_flac" / "eac_baseline_police_classics.log"
)


def _sample_log() -> RipLog:
    return RipLog(
        log_creator="cyanrip 0.9.3",
        creation_date="2026-06-28",
        ripping_info=RippingInfo(
            drive="PIONEER BD-RW BDR-209D",
            defeat_audio_cache=True,
            read_offset_correction=667,
            overread_lead_out=False,
            # cyanrip's ACTUAL text, verbatim from a real 0.9.3 rip. It used to be
            # EAC's phrase here, which meant the gap-handling row was handed its
            # expected output as input and no test could see that the renderer
            # never produced it (found on hardware, 2026-07-30).
            gap_detection="None signalled",
        ),
        tracks=(
            TrackResult(
                number=1,
                filename="01 - Roxanne.flac",
                peak_level=0.942,
                extraction_speed=1.6,
                extraction_quality=100.0,
                test_crc="b0d122e7",
                copy_crc="b0d122e7",
                status="ripped successfully",
                accuraterip_v2=AccurateRipResult(
                    version=2,
                    result="accurately ripped, confidence 200",
                    confidence=200,
                    local_crc="22B9924D",
                ),
            ),
            TrackResult(
                number=2,
                filename="02 - Message.flac",
                copy_crc="DEADBEEF",
                status="ripped successfully",
                accuraterip_v1=AccurateRipResult(
                    version=1, result="not found", confidence=None
                ),
            ),
        ),
        accuraterip_summary="13/14 tracks ripped accurately (AccurateRip)",
        health_status="No errors occurred",
    )


def test_first_line_attributes_to_platterpus_not_eac() -> None:
    text = render_eac_style_log(_sample_log())
    first = text.splitlines()[0]
    assert first.startswith("Exact Audio Copy-compatible log generated by Platterpus")
    # Unmistakable in a head/at-a-glance: it says NOT genuine somewhere up top.
    head = "\n".join(text.splitlines()[:6])
    assert "NOT a genuine EAC log" in head


def test_never_emits_a_fake_eac_checksum_signature() -> None:
    text = render_eac_style_log(_sample_log())
    # A real EAC log ends with "==== Log checksum <64 hex> ====". We must never
    # produce that — it is EAC's signature and forging it is the whole no-go.
    assert not re.search(r"==== Log checksum [0-9A-Fa-f]{64} ====", text)
    assert "NOT signed by Exact Audio Copy" in text


def test_roundtrips_through_our_parity_reader() -> None:
    # Detected as EAC-format AND the Copy CRCs read straight back out, so the
    # rendered log can be diffed/compared against a real EAC baseline.
    text = render_eac_style_log(_sample_log())
    assert looks_like_eac_log(text)
    assert track_copy_crcs(text) == {1: "B0D122E7", 2: "DEADBEEF"}


def test_accuraterip_line_uses_shared_confidence_rule() -> None:
    text = render_eac_style_log(_sample_log())
    # Track 1: a real confidence-200 match -> "Accurately ripped".
    assert "Accurately ripped (confidence 200)" in text
    assert "[22B9924D]" in text and "(AR v2)" in text
    # Track 2: confidence None -> NOT claimed as verified.
    assert "Track not present in AccurateRip database" in text


def test_renders_read_settings_block() -> None:
    text = render_eac_style_log(_sample_log())
    assert "Read offset correction" in text and "667" in text
    assert "Defeat audio cache      : Yes" in text
    assert "PIONEER BD-RW BDR-209D" in text


def test_gap_row_translates_cyanrips_detection_into_eacs_policy_wording() -> None:
    """The row must say what EAC says, from what cyanrip actually prints.

    cyanrip reports what the TOC *signalled*; EAC's row states the *policy*. Given
    cyanrip's real "None signalled", the row must read EAC's own phrase for that
    case — verified verbatim against a genuine EAC 1.1 log — and must not leak
    cyanrip's wording, which is what shipped in v0.5.18 and was caught on the rig.
    """
    text = render_eac_style_log(_sample_log())
    assert (
        "Gap handling                                : "
        "Not detected, thus appended to previous track" in text
    )
    # The leak is the failure mode, so assert on it directly: reverting the fix
    # puts cyanrip's phrase back in this row.
    assert "None signalled" not in text


def test_gap_row_drops_the_not_detected_caveat_when_gaps_were_signalled() -> None:
    """Same policy, no detection caveat — EAC's other real value for this row."""
    log = _sample_log()
    signalled = replace(
        log,
        ripping_info=replace(log.ripping_info, gap_detection="Track 2: 00:02:00"),
    )
    text = render_eac_style_log(signalled)
    assert (
        "Gap handling                                : Appended to previous track"
        in text
    )
    assert "Not detected" not in text


def test_gap_row_is_unreported_for_a_log_from_another_ripper() -> None:
    """A non-cyanrip log's gap policy is not knowable from its parsed text.

    The old code echoed whatever the field held — for a legacy whipper log that is
    a cdrdao version string, which is an engine name in a policy field.
    """
    log = _sample_log()
    other = replace(
        log,
        log_creator="whipper 0.10.0",
        ripping_info=replace(
            log.ripping_info, gap_detection="cdrdao version 1.2.4 from 2020"
        ),
    )
    text = render_eac_style_log(other)
    assert f"Gap handling                                : {_UNREPORTED}" in text
    assert "cdrdao" not in text


def test_gap_row_vocabulary_comes_from_a_real_eac_log_not_from_us() -> None:
    """Anchor the row's wording to genuine EAC output, and pin the real disagreement.

    Two claims, both from the committed real EAC 1.8 log of the same disc in the
    same drive (`output_reference/EAC_flac/`) rather than from our hand-authored
    fixture — a file we wrote is not evidence of EAC's vocabulary:

    1. "Appended to previous track" is EAC's actual string, character for
       character. (The "Not detected, thus …" variant was verified separately
       against a public EAC 1.1 log; EAC prints it only when its gap pass finds
       nothing, which did not happen on this disc.)
    2. EAC **detected pregaps here and cyanrip did not** — EAC lists `Pre-gap
       length` rows, cyanrip reports "None signalled". So our log legitimately
       differs from EAC's on this row, and the fix must not be "make the string
       match": that would hide a measurable archival gap (KDD-32 / `INDEX 00`).
    """
    eac = _EAC_BASELINE.read_bytes().decode("utf-16")
    # The baseline is two concatenated EAC runs of the same disc (20:01 and
    # 20:02), so expect one row per run and require them to agree.
    gap_rows = [ln for ln in eac.splitlines() if ln.startswith("Gap handling")]
    # Floor: a check that passes by finding nothing is decoration.
    assert gap_rows, "the real EAC baseline must carry a Gap handling row"
    assert all(ln.endswith(": Appended to previous track") for ln in gap_rows)

    pregaps = [ln for ln in eac.splitlines() if "Pre-gap length" in ln]
    assert len(pregaps) >= 2, "EAC must be shown detecting real pregaps on this disc"

    cyanrip_log = _CYANRIP_REFERENCE.read_text(encoding="utf-8", errors="replace")
    assert "None signalled" in cyanrip_log, (
        "the committed cyanrip log of the SAME disc must still show it detecting "
        "nothing — if this changes, the disagreement below has closed and the row's "
        "reasoning needs revisiting"
    )


def test_records_software_provenance_when_supplied() -> None:
    """Platterpus version+build and the FLAC/derived encoder versions appear in
    the attribution header when passed — the archival provenance fix — while the
    honesty guardrails (no fake EAC banner, no checksum, NOT-signed footer) hold.
    """
    text = render_eac_style_log(
        _sample_log(),
        platterpus_version="0.4.18",
        build_fingerprint="abc1234",
        encoder_versions={"flac": "1.5.0", "metaflac": "1.5.0", "ffmpeg": "8.1.1"},
    )
    assert "Generated by Platterpus 0.4.18 (build abc1234)." in text
    assert "FLAC encoder: flac 1.5.0, metaflac 1.5.0." in text
    assert "Derived-format encoder: ffmpeg 8.1.1." in text
    # cyanrip source line is still the genuine parsed one, not forged.
    assert "Rendered from a rip by cyanrip 0.9.3." in text
    # Honesty guardrails unchanged.
    assert "NOT signed by Exact Audio Copy" in text
    assert not re.search(r"Exact Audio Copy V\d", text)  # no fake version banner
    assert not re.search(r"==== Log checksum [0-9A-Fa-f]{64} ====", text)


def test_omits_provenance_lines_when_not_supplied() -> None:
    """Absent values are omitted, never invented (the honesty gate). ffmpeg is
    left out for a FLAC-only rip (no derived-format encoder ran)."""
    # Nothing supplied → none of the new lines appear (back-compat with callers
    # that don't pass provenance).
    bare = render_eac_style_log(_sample_log())
    assert "Generated by Platterpus" not in bare
    assert "FLAC encoder:" not in bare
    assert "Derived-format encoder" not in bare
    # FLAC-only: flac/metaflac present, ffmpeg omitted because it wasn't supplied.
    flac_only = render_eac_style_log(
        _sample_log(),
        platterpus_version="0.4.18",
        encoder_versions={"flac": "1.5.0", "metaflac": "1.5.0"},
    )
    assert "FLAC encoder: flac 1.5.0, metaflac 1.5.0." in flac_only
    assert "Derived-format encoder" not in flac_only
    # No build fingerprint supplied → the "(build …)" suffix is dropped.
    assert "Generated by Platterpus 0.4.18." in flac_only


def test_never_raises_with_provenance_on_partial_log() -> None:
    """The never-raises contract holds even with provenance kwargs on an empty
    RipLog."""
    text = render_eac_style_log(
        RipLog(),
        platterpus_version="0.4.18",
        build_fingerprint="abc1234",
        encoder_versions={"flac": "1.5.0"},
    )
    assert text.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "NOT signed by Exact Audio Copy" in text


def test_does_not_fabricate_read_mode_or_c2_pointers() -> None:
    """Regression (#32), restated for the EAC-layout export (2026-07-27).

    Originally this asserted the rows were *absent*, because the parser had no
    field behind them and a hardcoded "Secure"/"No" would have been invented rip
    facts. The maintainer's later direction — match EAC's layout as closely as
    the data allows, and label what we can't fill — changes the remedy, not the
    rule: the rows now appear in EAC's position, and an unreported value reads
    ``(not reported by the ripper)``. What must never happen is the invented value,
    so that is what this pins.

    The values themselves are real when cyanrip does report them: see
    ``tests/test_eac_layout_parity.py``, where C2 renders "No" from cyanrip's
    "C2 errors: unsupported by drive" and Read mode renders "Secure" from its
    paranoia level.
    """
    # A log with neither fact reported (this fixture has no paranoia/C2 lines).
    text = render_eac_style_log(_sample_log())
    assert "Read mode               : (not reported by the ripper)" in text
    assert "Make use of C2 pointers : (not reported by the ripper)" in text
    # The invented values the original regression was about:
    assert "Read mode               : Secure" not in text
    assert "Make use of C2 pointers : No" not in text


def test_never_raises_on_empty_or_partial_log() -> None:
    # An empty RipLog still yields a valid, attributed, unsigned log.
    text = render_eac_style_log(RipLog())
    assert text.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "NOT signed by Exact Audio Copy" in text
    # A partial track (Nones everywhere) must not crash the formatter.
    partial = RipLog(tracks=(TrackResult(number=1),))
    out = render_eac_style_log(partial)
    assert "Track  1" in out
    assert "Track not present in AccurateRip database" in out


# --- Integrity checksum (KDD-28): honest, openly-verifiable, not EAC's --------


def _checksum_line(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("==== Platterpus log checksum "):
            return line
    raise AssertionError("no Platterpus checksum footer found")


def test_emits_a_platterpus_integrity_checksum_footer() -> None:
    """The log ends with OUR own checksum line — named as Platterpus's, naming
    SHA-256, and explicitly not an EAC checksum."""
    text = render_eac_style_log(_sample_log())
    line = _checksum_line(text)
    assert "SHA-256" in line
    assert "NOT an EAC checksum" in line
    # A lowercase 64-hex digest is present.
    assert re.search(r"\b[0-9a-f]{64}\b", line)
    # It is the very last content line (EAC puts its checksum last, too).
    assert text.rstrip("\n").splitlines()[-1] == line


def test_checksum_is_never_eacs_marker() -> None:
    """Our footer must never be readable as EAC's `==== Log checksum <hex> ====`
    signature — forging that is the whole no-go."""
    text = render_eac_style_log(_sample_log())
    assert not re.search(r"==== Log checksum [0-9A-Fa-f]{64} ====", text)
    # Ours starts with "Platterpus", not "Log checksum".
    assert _checksum_line(text).startswith("==== Platterpus log checksum ")


def test_checksum_is_openly_verifiable_with_a_plain_sha256() -> None:
    """The hex is a plain SHA-256 of every byte above the footer — reproducible
    with any standard tool and no secret key (unlike EAC's obfuscated hash).
    This is the `head -n -1 <log> | sha256sum` recipe expressed in Python."""
    text = render_eac_style_log(_sample_log())
    lines = text.splitlines(keepends=True)
    # Everything except the final (checksum) line is the hashed body.
    body = "".join(lines[:-1])
    expected = hashlib.sha256(body.encode("utf-8")).hexdigest()
    assert expected in _checksum_line(text)


def test_verify_accepts_an_untouched_log() -> None:
    text = render_eac_style_log(_sample_log())
    assert verify_eac_style_log_checksum(text) is True


def test_verify_rejects_a_tampered_log() -> None:
    """Changing any byte above the footer breaks the checksum — the whole point
    of tamper-evidence. Equal in strength to EAC's guarantee."""
    text = render_eac_style_log(_sample_log())
    # Flip a real data value in the body (a Copy CRC) after rendering.
    tampered = text.replace("DEADBEEF", "DEADBEE0")
    assert tampered != text
    assert verify_eac_style_log_checksum(tampered) is False


def test_verify_returns_none_without_our_footer() -> None:
    """A real EAC log (or any text lacking our footer) yields None, not a false
    positive/negative — verification only speaks to logs we produced."""
    # A genuine EAC log carries no Platterpus footer. (The committed baseline is
    # UTF-16 like real EAC output, so decode it the way our parser would.)
    real_eac = _EAC_BASELINE.read_text(encoding="utf-16")
    assert verify_eac_style_log_checksum(real_eac) is None
    assert verify_eac_style_log_checksum("not a log at all") is None
    # Our own log with the footer line removed also has nothing to check.
    ours = render_eac_style_log(_sample_log())
    footerless = "\n".join(
        line
        for line in ours.splitlines()
        if not line.startswith("==== Platterpus log checksum ")
    )
    assert verify_eac_style_log_checksum(footerless) is None


def test_verify_never_raises_on_garbage() -> None:
    for junk in ("", "\x00\x00", "==== Platterpus log checksum (no hex here) ===="):
        # Must return a value (None/bool), never raise.
        assert verify_eac_style_log_checksum(junk) in (True, False, None)


# --- Test & Copy CRC pair (KDD-30) ------------------------------------------


def _rip_log(track: TrackResult) -> RipLog:
    return RipLog(log_creator="cyanrip 0.9.3", tracks=(track,))


def test_converged_track_renders_test_and_copy_pair() -> None:
    """A track confirmed by ≥2 agreeing secure re-reads gets an EAC-style
    Test CRC == Copy CRC pair, with an honest 'how' note."""
    text = render_eac_style_log(
        _rip_log(
            TrackResult(
                number=1, copy_crc="a1b2c3d4", rip_count=2, secure_rerip_converged=True
            )
        )
    )
    assert "Test CRC A1B2C3D4" in text
    assert "Copy CRC A1B2C3D4" in text
    # Honest about the mechanism — not a claim of two literal EAC passes.
    assert "confirmed across 2 secure re-reads" in text


def test_single_read_track_has_no_fabricated_test_crc() -> None:
    """A single-read track (no -Z, or a clean track on the fast path) shows only
    a Copy CRC — we never invent a second 'test' read that didn't happen."""
    text = render_eac_style_log(_rip_log(TrackResult(number=1, copy_crc="deadbeef")))
    assert "Copy CRC DEADBEEF" in text
    assert "Test CRC" not in text


def test_converged_flag_alone_renders_the_pair() -> None:
    # secure_rerip_converged True is enough even if the rip count wasn't parsed.
    text = render_eac_style_log(
        _rip_log(
            TrackResult(number=1, copy_crc="cafebabe", secure_rerip_converged=True)
        )
    )
    assert "Test CRC CAFEBABE" in text and "Copy CRC CAFEBABE" in text


def test_native_dual_read_crc_is_rendered_as_is() -> None:
    # A backend that reports a genuinely distinct test_crc (whipper) is shown
    # verbatim, not synthesized.
    text = render_eac_style_log(
        _rip_log(TrackResult(number=1, test_crc="11111111", copy_crc="22222222"))
    )
    assert "Test CRC 11111111" in text
    assert "Copy CRC 22222222" in text


# --- CLI: scripts/render_eac_log.py ---------------------------------------


def _load_cli():
    spec = importlib.util.spec_from_file_location(
        "render_eac_log_cli", _REPO_ROOT / "scripts" / "render_eac_log.py"
    )
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_cli_renders_committed_cyanrip_log(capsys) -> None:
    cli = _load_cli()
    rc = cli.main([str(_CYANRIP_REFERENCE)])
    out = capsys.readouterr().out
    assert rc == 0
    assert out.splitlines()[0].startswith("Exact Audio Copy-compatible")
    assert "B0D122E7" in out  # track 1 Copy CRC carried through
    assert "NOT signed by Exact Audio Copy" in out


def test_cli_writes_output_file(tmp_path: Path, capsys) -> None:
    cli = _load_cli()
    dest = tmp_path / "rendered.log"
    rc = cli.main([str(_CYANRIP_REFERENCE), "-o", str(dest)])
    assert rc == 0
    written = dest.read_text(encoding="utf-8")
    assert looks_like_eac_log(written)
    assert track_copy_crcs(written)[1] == "B0D122E7"


def test_cli_refuses_a_real_eac_log(capsys) -> None:
    # Rendering an EAC log into "EAC style" is meaningless — and we won't
    # round-trip a real EAC log into our attributed format. Exit non-zero.
    cli = _load_cli()
    rc = cli.main([str(_EAC_BASELINE)])
    assert rc == 2
    assert "already looks like an EAC log" in capsys.readouterr().err


def test_cli_missing_file_returns_2(tmp_path: Path) -> None:
    cli = _load_cli()
    assert cli.main([str(tmp_path / "nope.log")]) == 2


# --- Offset-variant AccurateRip (real-hardware regression, 2026-07-26) --------


def _offset_variant_track() -> TrackResult:
    """Tracks 3 & 5 of the Police "Classics" rip: no exact AR match, but a
    confidence-200 match against the +450 offset-variant pressing."""
    return TrackResult(
        number=3,
        copy_crc="52dfdf7d",
        accuraterip_v1=AccurateRipResult(
            version=1, result="not found", confidence=None
        ),
        accuraterip_v2=AccurateRipResult(
            version=2, result="not found", confidence=None
        ),
        accuraterip_offset=AccurateRipResult(
            version=1,
            result="matches Accurip DB, confidence 200, track is partially accurately ripped",
            confidence=200,
            local_crc="BF62B1DA",
        ),
    )


def test_offset_variant_is_not_reported_as_absent_from_the_database() -> None:
    """REGRESSION: the renderer only looked at AR v2/v1, so an offset-variant match
    fell through to "Track not present in AccurateRip database" — factually FALSE
    (the track IS in the DB at confidence 200) and contradicting both the GUI
    verdict banner and the JSON report built from the same parsed RipLog."""
    text = render_eac_style_log(_rip_log(_offset_variant_track()))
    assert "not present in AccurateRip database" not in text
    assert "offset-variant" in text
    assert "partially accurate" in text
    assert "confidence 200" in text
    assert "BF62B1DA" in text  # the matched CRC is evidence, so it's shown


def test_offset_variant_never_claims_a_plain_accurate_rip() -> None:
    """It must not over-claim either: offset-variant is deliberately NOT "verified"
    (KDD-27), so the exact-match wording must be absent."""
    text = render_eac_style_log(_rip_log(_offset_variant_track()))
    assert "Accurately ripped (confidence" not in text


def test_a_genuinely_absent_track_still_says_not_present() -> None:
    # The fallback must survive: no exact match AND no offset-variant match.
    text = render_eac_style_log(
        _rip_log(
            TrackResult(
                number=1,
                copy_crc="deadbeef",
                accuraterip_v1=AccurateRipResult(
                    version=1, result="not found", confidence=None
                ),
            )
        )
    )
    assert "Track not present in AccurateRip database" in text


def test_overread_renders_yes_when_the_log_reported_it() -> None:
    """REGRESSION: rendered "(unknown)" while cyanrip had stated the mode outright."""
    log = RipLog(
        log_creator="cyanrip 0.9.3",
        ripping_info=RippingInfo(overread_lead_out=True),
        tracks=(TrackResult(number=1, copy_crc="aa"),),
    )
    assert "Overread into Lead-In and Lead-Out          : Yes" in render_eac_style_log(
        log
    )


# --- Incomplete-rip notice (real-hardware regression, 2026-07-26) ------------


def test_interrupted_rip_is_declared_not_silently_complete() -> None:
    """REGRESSION: a force-stopped 14-track rip rendered as 13 tidy "Copy OK"
    blocks with an empty conclusive section and a VALID integrity checksum — a
    self-attested archival record that read as a clean, complete rip of a 13-track
    disc. The app knew the outcome (the JSON report said "cancelled"); the log
    simply wasn't told."""
    log = RipLog(
        log_creator="cyanrip 0.9.3",
        tracks=tuple(TrackResult(number=n, copy_crc=f"{n:08x}") for n in range(1, 14)),
    )
    text = render_eac_style_log(log, outcome_status="cancelled", disc_track_total=14)
    assert "INCOMPLETE RIP (cancelled)" in text
    assert "13 of 14 disc tracks" in text
    assert "remaining 1 track(s) were never extracted" in text
    # The notice sits ABOVE the checksum, so it's covered by it and can't be
    # stripped without breaking verification.
    assert verify_eac_style_log_checksum(text) is True
    body = text.split("==== Platterpus log checksum")[0]
    assert "INCOMPLETE RIP" in body


def test_successful_rip_gets_no_incomplete_banner() -> None:
    log = RipLog(log_creator="cyanrip 0.9.3", tracks=(TrackResult(number=1),))
    assert "INCOMPLETE" not in render_eac_style_log(
        log, outcome_status="success", disc_track_total=1
    )


def test_unknown_outcome_renders_no_banner() -> None:
    """Old callers (and the render_eac_log.py CLI) pass no outcome — they must
    behave exactly as before rather than gaining a guessed banner."""
    log = RipLog(log_creator="cyanrip 0.9.3", tracks=(TrackResult(number=1),))
    assert "INCOMPLETE" not in render_eac_style_log(log)


def test_absent_conclusive_report_is_stated_without_inventing_a_cause() -> None:
    """An empty conclusive section is itself a fact. But this also fires for a
    successful-but-trimmed log, so it must NOT assert that the ripper was stopped —
    that cause belongs to the INCOMPLETE banner, which only appears when the
    caller actually told us the outcome."""
    log = RipLog(log_creator="cyanrip 0.9.3", tracks=(TrackResult(number=1),))
    text = render_eac_style_log(log)  # no health_status, no accuraterip_summary
    assert "Conclusive status report : absent" in text
    assert "stopped" not in text.lower()


def test_conclusive_report_is_rendered_normally_when_present() -> None:
    """A log that HAS an end-of-rip summary renders it, in EAC's own wording.

    The "absent" line is reserved for a log that genuinely carries no summary;
    the wording moved from our own "Health status :" row to EAC's bare sentences
    when the export was aligned to EAC's layout (2026-07-27).
    """
    text = render_eac_style_log(_sample_log())
    assert "Conclusive status report : absent" not in text
    assert "No errors occurred" in text
    assert "End of status report" in text
