"""`bom.cdx.json` and its block in `DEPENDENCIES.md` must be what the code says today.

The maintainer asked (2026-10-05) for *"a full map out of what projects /
languages / versions / applications / dependencies you have or rely on"*, kept
*"somewhere standard that you and other applications can see and use"*. The map
is a CycloneDX 1.7 BOM plus a human-readable block, both GENERATED by
``scripts/emit_bom.py`` from the code that enforces each fact. A hand-kept map
is only ever wrong by omission, and nobody reviews a document for what is not in
it — so this file is what makes the promise checkable:

* **staleness** — the committed JSON and the committed Markdown block are
  byte-identical to a fresh run (same mechanism as
  ``tests/test_dependency_contract_emitted.py``);
* **determinism** — a run under a different ``HOME`` and hash seed produces the
  same bytes, so the staleness check cannot fail at random;
* **non-triviality** — floors, and named members that must be present, because
  "the file equals the generator" is satisfied perfectly by an empty generator;
* **coverage, checked independently** — every pyproject dependency, every
  registry entry, every GitHub Action pin and every tool the code looks up is
  re-derived HERE by a different method (plain text and ``tomllib``, not the
  generator's AST walkers) and required in the BOM, because two implementations
  sharing one ancestor share its bugs;
* **structure** — CycloneDX's shape, asserted field by field. **This is not
  JSON-schema validation**: no schema validator is a dependency of this project,
  and adding one needs the maintainer's approval. The assertions below cover
  every field the generator writes.

Regenerate with ``python3 scripts/emit_bom.py``.
"""

from __future__ import annotations

import importlib.util
import json
import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from types import ModuleType
from typing import Final

import pytest

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
_SCRIPT: Final[Path] = REPO_ROOT / "scripts" / "emit_bom.py"
_BOM: Final[Path] = REPO_ROOT / "bom.cdx.json"
_DEPENDENCIES: Final[Path] = REPO_ROOT / "DEPENDENCIES.md"

# Floors, set well under today's counts (measured 2026-10-05: 90 components,
# 15 services, 28 external programs, 6 actions) so ordinary work does not trip
# them. They catch collapse, not change.
_MIN_COMPONENTS: Final[int] = 60
_MIN_SERVICES: Final[int] = 10
_MIN_HOST_TOOLS: Final[int] = 20
_MIN_ACTIONS: Final[int] = 4

#: The CycloneDX 1.7 values this generator may write. Every one also exists in
#: 1.6; anything outside these sets is a typo or a field nobody checked.
_COMPONENT_TYPES: Final[frozenset[str]] = frozenset(
    {
        "application",
        "framework",
        "library",
        "container",
        "platform",
        "operating-system",
        "device",
        "device-driver",
        "firmware",
        "file",
        "machine-learning-model",
        "data",
        "cryptographic-asset",
    }
)
_SCOPES: Final[frozenset[str]] = frozenset({"required", "optional", "excluded"})
_REF_TYPES: Final[frozenset[str]] = frozenset(
    {"vcs", "website", "distribution", "documentation", "other", "release-notes"}
)
_FLOWS: Final[frozenset[str]] = frozenset(
    {"inbound", "outbound", "bi-directional", "unknown"}
)
#: Keys each object may carry. A whitelist rather than a spot check, so a
#: misspelt key (``dependOn``) fails instead of being silently ignored by
#: every consumer.
_TOP_KEYS: Final[frozenset[str]] = frozenset(
    {
        "$schema",
        "bomFormat",
        "specVersion",
        "version",
        "metadata",
        "components",
        "services",
        "dependencies",
    }
)
_COMPONENT_KEYS: Final[frozenset[str]] = frozenset(
    {
        "type",
        "bom-ref",
        "group",
        "name",
        "version",
        "versionRange",
        "isExternal",
        "description",
        "scope",
        "purl",
        "pedigree",
        "externalReferences",
        "properties",
    }
)
_SERVICE_KEYS: Final[frozenset[str]] = frozenset(
    {
        "bom-ref",
        "provider",
        "name",
        "description",
        "endpoints",
        "authenticated",
        "x-trust-boundary",
        "data",
        "externalReferences",
        "properties",
    }
)


def _load_generator() -> ModuleType:
    """Import the script by path — ``scripts/`` is not an importable package."""
    spec = importlib.util.spec_from_file_location("emit_bom", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    return _load_generator()


@pytest.fixture(scope="module")
def committed() -> dict[str, object]:
    data = json.loads(_BOM.read_text(encoding="utf-8"))
    assert isinstance(data, dict)
    return data


def _components(bom: dict[str, object]) -> list[dict[str, object]]:
    items = bom["components"]
    assert isinstance(items, list)
    return items


def _services(bom: dict[str, object]) -> list[dict[str, object]]:
    items = bom["services"]
    assert isinstance(items, list)
    return items


def _props(item: dict[str, object]) -> dict[str, str]:
    props = item.get("properties", [])
    assert isinstance(props, list)
    return {str(p["name"]): str(p["value"]) for p in props}


# --- Staleness and determinism ---------------------------------------------------


def test_the_committed_bom_is_what_the_code_generates(generator: ModuleType) -> None:
    """The whole point. If this fails, regenerate — do not edit the file."""
    assert _BOM.read_text(encoding="utf-8") == generator.render_json(), (
        "bom.cdx.json is stale — regenerate it with\n"
        "    python3 scripts/emit_bom.py\n"
        "and commit it with the change that moved it."
    )


def test_the_committed_markdown_block_is_what_the_code_generates(
    generator: ModuleType,
) -> None:
    document = _DEPENDENCIES.read_text(encoding="utf-8")
    assert document.count(generator.BEGIN_MARKER) == 1, "expected one BEGIN marker"
    assert document.count(generator.END_MARKER) == 1, "expected one END marker"
    assert generator.committed_block(document) == generator.render_markdown(), (
        "the generated block in DEPENDENCIES.md is stale — regenerate it with\n"
        "    python3 scripts/emit_bom.py"
    )


def test_a_run_elsewhere_produces_the_same_bytes(tmp_path: Path) -> None:
    """Determinism, measured where it could fail: another process, another
    ``HOME`` (the registry's binary paths are computed from it) and another hash
    seed (set iteration order). A cached second call in this process would prove
    nothing. Also asserts the run writes nothing into ``HOME``."""
    env = {**os.environ, "HOME": str(tmp_path), "PYTHONHASHSEED": "4242"}
    run = subprocess.run(
        [sys.executable, str(_SCRIPT), "--stdout"],
        env=env,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    assert run.returncode == 0, run.stderr
    assert run.stdout == _BOM.read_text(encoding="utf-8"), (
        "the generator's output depends on the machine or on hash order"
    )
    assert not list(tmp_path.iterdir()), "the generator wrote into HOME"


def test_check_mode_can_fail_not_only_pass(
    generator: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--check`` must be able to return 1 for EITHER output going stale."""
    assert generator.main(["--check"]) == 0

    monkeypatch.setattr(generator, "OUTPUT_PATH", tmp_path / "absent.json")
    assert generator.main(["--check"]) == 1
    monkeypatch.undo()

    stale_doc = tmp_path / "DEPENDENCIES.md"
    stale_doc.write_text(
        _DEPENDENCIES.read_text(encoding="utf-8").replace(
            "| Category | Entries |", "| Category | Count |"
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(generator, "MARKDOWN_PATH", stale_doc)
    assert generator.main(["--check"]) == 1


# --- What the document declares ------------------------------------------------------


def test_it_declares_cyclonedx_1_7(committed: dict[str, object]) -> None:
    assert committed["bomFormat"] == "CycloneDX"
    assert committed["specVersion"] == "1.7"
    assert committed["$schema"] == "http://cyclonedx.org/schema/bom-1.7.schema.json"
    assert committed["version"] == 1
    assert set(committed) <= _TOP_KEYS, set(committed) - _TOP_KEYS
    metadata = committed["metadata"]
    assert isinstance(metadata, dict)
    # Determinism by design: either would change on every run.
    assert "timestamp" not in metadata
    assert "serialNumber" not in committed
    assert metadata["lifecycles"] == [{"phase": "pre-build"}]



def test_it_is_valid_cyclonedx_1_7_by_the_published_schema() -> None:
    """The map passes the CycloneDX 1.7 JSON schema, strict, checked offline.

    `test_it_declares_cyclonedx_1_7` checks what the file SAYS it is; this checks
    that it IS, against the schema CycloneDX publishes, which
    `cyclonedx-python-lib` bundles with the SPDX and JSF schemas it references, so
    no network is needed. Strict mode refuses keys the schema does not define, so
    a field our generator invents fails here instead of in a consumer's tool.
    (Dev-only dependency, approved 2026-10-05, `PLANNING.md` KDD-41, C7.)
    """
    from cyclonedx.schema import SchemaVersion
    from cyclonedx.validation.json import JsonStrictValidator

    validator = JsonStrictValidator(SchemaVersion.V1_7)
    error = validator.validate_str(_BOM.read_text(encoding="utf-8"))
    assert error is None, f"bom.cdx.json is not valid CycloneDX 1.7: {error}"
    # Non-triviality: the validator refuses a document that breaks the schema, so
    # a None above is the schema's verdict, not a validator that accepts anything.
    broken = json.loads(_BOM.read_text(encoding="utf-8"))
    broken["components"][0]["type"] = "not-a-component-type"
    assert validator.validate_str(json.dumps(broken)) is not None


def test_it_names_the_version_it_describes(committed: dict[str, object]) -> None:
    """Why the generator is re-run after a version bump (CLAUDE.md step 5)."""
    from platterpus import __version__

    metadata = committed["metadata"]
    assert isinstance(metadata, dict)
    component = metadata["component"]
    assert component["name"] == "platterpus"
    assert component["version"] == __version__
    assert component["purl"] == f"pkg:pypi/platterpus@{__version__}"
    assert component["licenses"] == [{"expression": "GPL-3.0-only"}]


def test_the_map_is_not_empty(generator: ModuleType, committed: dict) -> None:
    """Floors. Every assertion above is "the file matches the generator", which
    an empty generator satisfies."""
    components = _components(committed)
    services = _services(committed)
    assert len(components) >= _MIN_COMPONENTS, len(components)
    assert len(services) >= _MIN_SERVICES, len(services)
    by_category: dict[str, int] = {}
    for item in [*components, *services]:
        category = _props(item)["platterpus:category"]
        by_category[category] = by_category.get(category, 0) + 1
    expected = {key for key, _title in generator.CATEGORIES}
    assert set(by_category) == expected, set(by_category) ^ expected
    assert by_category["host-tool"] >= _MIN_HOST_TOOLS
    assert by_category["ci-action"] >= _MIN_ACTIONS


# --- Named members (the subject, not only the shape) ---------------------------------


def test_the_cyanrip_fork_is_present_at_the_current_pin(committed: dict) -> None:
    from platterpus.deps import fork_source

    repo = fork_source.FORK_REPO_URL.removesuffix(".git")
    slug = repo.removeprefix("https://github.com/")
    forks = [
        c
        for c in _components(committed)
        if c.get("purl") == f"pkg:github/{slug}@{fork_source.FORK_PIN}"
    ]
    assert len(forks) == 1, "the production fork pin is not in the BOM"
    fork = forks[0]
    assert fork["version"] == fork_source.FORK_EXPECTED_VERSION
    assert fork["scope"] == "required"
    props = _props(fork)
    assert props["platterpus:pin"] == fork_source.FORK_PIN
    assert props["platterpus:build-tag"] == fork_source.FORK_EXPECTED_BUILD_TAG
    assert fork_source.PIN_UNDER_REVIEW in props["platterpus:pin-under-review"]
    refs = fork["externalReferences"]
    assert isinstance(refs, list)
    assert any(r["type"] == "vcs" and r["url"].startswith(repo) for r in refs)
    # The shared seam texts travel with the partner project.
    docs = {r["url"].rsplit("/", 1)[1] for r in refs if r["type"] == "documentation"}
    assert {"handshake-protocol.md", "seam-rules.md"} <= docs, docs
    # The fork's ancestor is upstream cyanrip.
    ancestors = fork["pedigree"]["ancestors"]
    assert [a["purl"] for a in ancestors] == ["pkg:github/cyanreg/cyanrip"]


def _norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _requirement_name(text: str) -> str:
    match = re.match(r"\s*([A-Za-z0-9][A-Za-z0-9._-]*)", text)
    assert match, text
    return _norm(match.group(1))


def test_every_pyproject_dependency_is_present(committed: dict) -> None:
    """Re-read with ``tomllib`` here, not through the generator."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text("utf-8"))
    project = pyproject["project"]
    wanted = {
        "required": [_requirement_name(d) for d in project["dependencies"]],
        "excluded": [
            *(_requirement_name(d) for d in project["optional-dependencies"]["dev"]),
            *(_requirement_name(d) for d in pyproject["build-system"]["requires"]),
        ],
    }
    assert len(wanted["required"]) >= 5 and len(wanted["excluded"]) >= 6
    present = {
        str(c["purl"]).removeprefix("pkg:pypi/").split("@")[0]: c["scope"]
        for c in _components(committed)
        if str(c.get("purl", "")).startswith("pkg:pypi/")
    }
    for scope, names in wanted.items():
        for name in names:
            assert name in present, f"{name} (pyproject) is missing from the BOM"
            assert present[name] == scope, f"{name}: scope {present[name]} != {scope}"


def test_every_registry_dependency_is_present(committed: dict) -> None:
    """Critical rule #6's registry is the list of what the app probes at launch."""
    from platterpus.deps.registry import SPECS

    ids = {
        _props(c).get("platterpus:registry-id")
        for c in _components(committed)
        if "platterpus:registry-id" in _props(c)
    }
    purls = {str(c.get("purl", "")) for c in _components(committed)}
    names = {c["name"] for c in _components(committed)}
    for spec in SPECS:
        if spec.dep_id == "musicbrainzngs":
            assert any(p.startswith("pkg:pypi/musicbrainzngs") for p in purls)
        elif spec.dep_id == "cyanrip":
            assert "cyanrip" in names
        else:
            assert spec.dep_id in ids, f"registry entry {spec.dep_id} is missing"
    assert len(SPECS) >= 7


def test_every_github_action_is_present_with_its_pin(committed: dict) -> None:
    """Re-read from the workflow text with a plain regex."""
    pattern = re.compile(r"uses:\s*([^@\s]+)@([0-9a-f]{40})")
    pins: set[tuple[str, str]] = set()
    for workflow in sorted((REPO_ROOT / ".github" / "workflows").glob("*.yml")):
        pins |= set(pattern.findall(workflow.read_text(encoding="utf-8")))
    assert len(pins) >= _MIN_ACTIONS, pins
    present = {
        (f"{c['group']}/{c['name']}", _props(c)["platterpus:pinned-ref"])
        for c in _components(committed)
        if _props(c)["platterpus:category"] == "ci-action"
    }
    assert pins <= present, pins - present


#: Lookups of a tool by literal name, read from source TEXT — the generator
#: reads the AST, so a disagreement between the two is a finding about one of
#: them, not a tautology.
_LOOKUP: Final[re.Pattern[str]] = re.compile(
    r"\b(?:resolve_tool|find_tool|which|_which|_host_tool)\(\s*\"([A-Za-z0-9_.+-]+)\""
)


def test_every_tool_the_code_looks_up_is_in_the_map(committed: dict) -> None:
    looked_up: set[str] = set()
    for path in sorted((REPO_ROOT / "src" / "platterpus").rglob("*.py")):
        looked_up |= set(_LOOKUP.findall(path.read_text(encoding="utf-8")))
    assert len(looked_up) >= 8, looked_up
    names = {str(c["name"]) for c in _components(committed)}
    missing = sorted(looked_up - names)
    assert not missing, f"tools the code runs but the BOM omits: {missing}"


def test_every_service_url_constant_is_an_endpoint(committed: dict) -> None:
    """The URL constants in src, read here, must each be covered by an endpoint."""
    from platterpus.adapters import cover_art, ctdb_client
    from platterpus.deps import fork_source, ripper_manifest
    from platterpus.update_check import RELEASES_API_URL

    constants = [
        cover_art.COVER_URL_TEMPLATE.split("{", 1)[0],
        f"{ctdb_client.CTDB_SCHEME}://{ctdb_client.CTDB_HOST}{ctdb_client.LOOKUP_PATH}",
        RELEASES_API_URL,
        ripper_manifest.MANIFEST_URL,
        fork_source.FORK_REPO_URL,
    ]
    endpoints = {str(e) for s in _services(committed) for e in s.get("endpoints", [])}
    missing = [url for url in constants if url not in endpoints]
    assert not missing, f"service URLs absent from the BOM: {missing}"
    assert any("musicbrainz.org" in e for e in endpoints)


# --- Structure (in place of schema validation) ----------------------------------------


def test_the_structure_holds(committed: dict) -> None:
    components = _components(committed)
    services = _services(committed)
    metadata = committed["metadata"]
    refs = [str(c["bom-ref"]) for c in [*components, *services]]
    refs.append(str(metadata["component"]["bom-ref"]))
    assert len(refs) == len(set(refs)), "bom-refs must be unique"
    known = set(refs)

    for c in components:
        where = c["bom-ref"]
        assert set(c) <= _COMPONENT_KEYS, (where, set(c) - _COMPONENT_KEYS)
        assert c["type"] in _COMPONENT_TYPES, where
        assert isinstance(c["name"], str) and c["name"], where
        assert c["scope"] in _SCOPES, where
        # Mutually exclusive, and a range only on an external component.
        assert not ("version" in c and "versionRange" in c), where
        if "versionRange" in c:
            assert c.get("isExternal") is True, where
            assert str(c["versionRange"]).startswith("vers:"), where
        if "purl" in c:
            assert str(c["purl"]).startswith("pkg:"), where
            assert " " not in str(c["purl"]), where
    for s in services:
        where = s["bom-ref"]
        assert set(s) <= _SERVICE_KEYS, (where, set(s) - _SERVICE_KEYS)
        for endpoint in s.get("endpoints", []):
            assert re.match(r"^https?://[^\s{}]+$", endpoint), (where, endpoint)
        for flow in s.get("data", []):
            assert flow["flow"] in _FLOWS, where
            assert flow["classification"], where
        assert isinstance(s["authenticated"], bool)
    for item in [*components, *services]:
        for ref in item.get("externalReferences", []):
            assert ref["type"] in _REF_TYPES, (item["bom-ref"], ref)
            assert re.match(r"^https?://[^\s{}]+$", ref["url"]), ref
        for prop in item["properties"]:
            assert set(prop) == {"name", "value"}, prop
            assert isinstance(prop["value"], str), prop
            # Our own namespace; `cdx:` is CycloneDX's.
            assert prop["name"].startswith("platterpus:"), prop
    graph = committed["dependencies"]
    assert isinstance(graph, list) and len(graph) >= 5
    for edge in graph:
        assert set(edge) == {"ref", "dependsOn"}, edge
        assert edge["ref"] in known, edge["ref"]
        assert set(edge["dependsOn"]) <= known, set(edge["dependsOn"]) - known
    roots = [e for e in graph if e["ref"] == "platterpus"]
    assert len(roots) == 1 and len(roots[0]["dependsOn"]) >= 20


def test_the_markdown_and_the_json_describe_the_same_entries(committed: dict) -> None:
    """The relation between the two committed artifacts, checked on the files
    themselves rather than on the generator that wrote both."""
    document = _DEPENDENCIES.read_text(encoding="utf-8")
    block = document.split("<!-- BEGIN GENERATED: emit_bom.py", 1)[1]
    block = block.split("<!-- END GENERATED: emit_bom.py -->", 1)[0]
    components = _components(committed)
    services = _services(committed)
    assert f"**{len(components)} components and {len(services)} services**" in block
    for c in components:
        props = _props(c)
        label = (
            f"{c['group']}/{c['name']}"
            if props["platterpus:category"] == "ci-action"
            else c["name"]
        )
        assert f"| `{label}` |" in block, f"{label} is in the JSON, not the table"
    for s in services:
        assert f"| `{s['name']}` |" in block, s["name"]


def test_no_generated_row_can_be_mistaken_for_the_hand_kept_cyanrip_row() -> None:
    """``test_no_stale_version_claims`` finds THE cyanrip row by the prefix
    ``| cyanrip (``. The generated tables put every name in backticks so their
    cyanrip rows can never match that selector and be counted as a second one."""
    document = _DEPENDENCIES.read_text(encoding="utf-8")
    rows = [line for line in document.splitlines() if line.startswith("| cyanrip (")]
    assert len(rows) == 1


# --- The generator's own two-way check -------------------------------------------------


def test_a_tool_the_code_uses_without_a_note_stops_the_run(
    generator: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A new ``resolve_tool("x")`` must not slip into the code unmapped."""
    tool_entries = sys.modules["bommap.tool_entries"]
    real = dict(tool_entries.tool_lookups())
    monkeypatch.setattr(
        tool_entries,
        "tool_lookups",
        lambda: {**real, "frobnicate": ("src/platterpus/app.py",)},
    )
    with pytest.raises(generator.GeneratorError, match="frobnicate"):
        tool_entries._host_tool_entries()


def test_a_note_for_a_tool_the_code_no_longer_uses_stops_the_run(
    generator: ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    """…and a tool the code stopped using must not linger in the map."""
    tool_entries = sys.modules["bommap.tool_entries"]
    notes = dict(tool_entries._TOOL_NOTES)
    notes["retired-tool"] = tool_entries._ToolNote("used to do something")
    monkeypatch.setattr(tool_entries, "_TOOL_NOTES", notes)
    with pytest.raises(generator.GeneratorError, match="retired-tool"):
        tool_entries._host_tool_entries()


def test_a_witness_that_no_longer_holds_stops_the_run(generator: ModuleType) -> None:
    reading = sys.modules["bommap.reading"]
    with pytest.raises(generator.GeneratorError, match="no longer a string"):
        reading._require(
            "src/platterpus/app.py", "no-such-program-anywhere", why="probe"
        )
    # And holds where it should: `bash` is what --rig-session runs.
    assert reading._require("src/platterpus/app.py", "bash", why="probe")
