"""Render a parsed :class:`RipLog` into an EAC-*layout* text log.

**This is NOT a genuine EAC log and it is NEVER signed.** See
``docs/eac-log-and-repair-feasibility.md``: the EAC log checksum is an
attestation that *Exact Audio Copy* produced the rip, so signing our
(cyanrip/whipper) output as EAC would be **forging provenance** — a bannable
"faked log" on gazelle trackers and a direct violation of the project's
"never fake a log/checksum" rule. We do not do it.

What this *does* produce is an honest, conspicuously-attributed log that mirrors
EAC's section/per-track layout so a human can ``diff``/``meld`` it against a real
EAC log and see the per-track Copy CRCs line up — the readable companion to the
programmatic ``scripts/eac_parity.py`` check. Honesty guardrails enforced here:

* The very first line says it was generated by Platterpus and is **not** a
  genuine EAC log — visible at first glance and in any ``head``.
* No fake ``Exact Audio Copy Vx.y`` version banner and **no**
  ``==== Log checksum <hex> ====`` line; the footer is an explicit
  "not signed by Exact Audio Copy" marker in the checksum's place.
* Only real data from the rip is rendered — absent fields are omitted, never
  invented.

The output is still *detected as EAC-format* by our own parser
(``parsers/eac_log.looks_like_eac_log`` keys on the ``Exact Audio Copy`` banner
prefix, which "Exact Audio Copy-compatible…" satisfies), so the parity tooling
can read the Copy CRCs straight back out of it.

Like the parsers, this never raises on a partially-populated ``RipLog``.
"""

from __future__ import annotations

import logging

from platterpus.parsers.rip_log import (
    AccurateRipResult,
    RipLog,
    TrackResult,
    accuraterip_is_match,
)

log = logging.getLogger(__name__)

# The first line. It MUST start with "Exact Audio Copy" so our own EAC parser
# detects the format (the banner regex is `^Exact Audio Copy\b`, and the "-"
# after "Copy" is a word boundary), while making it unmistakable to a human
# that this was generated by us and is not a real EAC log.
_BANNER: str = "Exact Audio Copy-compatible log generated by Platterpus"

# Replaces EAC's `==== Log checksum <hex> ====`. Its presence (and the absence
# of a real checksum) is the honest tell that this log was not signed by EAC.
_NOT_SIGNED: str = (
    "==== This log was generated by Platterpus and is NOT signed by "
    "Exact Audio Copy ===="
)


def render_eac_style_log(rip_log: RipLog) -> str:
    """Return an EAC-layout, clearly-attributed text rendering of ``rip_log``.

    Never raises — a malformed/partial ``RipLog`` yields a best-effort log with
    a valid attribution header and footer (matching the never-raises discipline
    of the parsers this complements).
    """
    try:
        return _render(rip_log)
    except Exception:  # noqa: BLE001 — a formatter must never crash a caller
        log.exception("EAC-style log render failed; emitting minimal stub")
        return "\n".join([_BANNER, "", "(log could not be rendered)", "", _NOT_SIGNED])


def _render(rip_log: RipLog) -> str:
    info = rip_log.ripping_info
    source = rip_log.log_creator or "an unknown backend"
    lines: list[str] = [
        _BANNER,
        f"  Rendered from a rip by {source}.",
        "  This is NOT a genuine EAC log, carries no EAC log checksum, and must",
        "  not be presented as an EAC rip. It mirrors EAC's layout only so the",
        "  per-track Copy CRCs can be compared against a real EAC log.",
        "",
    ]
    if rip_log.creation_date:
        lines.append(f"Rip date : {rip_log.creation_date}")
        lines.append("")

    # --- Drive / read settings (EAC's archival block) ---
    if info.drive:
        lines.append(f"Used drive  : {info.drive}")
        lines.append("")
    lines.append("Read mode               : Secure")
    lines.append(f"Defeat audio cache      : {_yes_no(info.defeat_audio_cache)}")
    lines.append("Make use of C2 pointers : No")
    lines.append("")
    if info.read_offset_correction is not None:
        lines.append(
            f"Read offset correction                      : "
            f"{info.read_offset_correction}"
        )
    lines.append(
        f"Overread into Lead-In and Lead-Out          : {_yes_no(info.overread_lead_out)}"
    )
    if info.gap_detection:
        lines.append(
            f"Gap handling                                : {info.gap_detection}"
        )
    lines.append("")

    # --- Per-track blocks ---
    for track in rip_log.tracks:
        lines.extend(_track_block(track))

    # --- Conclusive report ---
    lines.append("")
    if rip_log.accuraterip_summary:
        lines.append(f"AccurateRip summary : {rip_log.accuraterip_summary}")
    if rip_log.health_status:
        lines.append(f"Health status       : {rip_log.health_status}")
    lines.append("")
    # Deliberately NOT a real "==== Log checksum <hex> ====": that is EAC's
    # signature, and signing our output as EAC would be forgery.
    lines.append(_NOT_SIGNED)
    return "\n".join(lines) + "\n"


def _track_block(track: TrackResult) -> list[str]:
    """The per-track section, matching EAC's shape (only real fields rendered)."""
    out: list[str] = [f"Track  {track.number}", ""]
    if track.filename:
        out.append(f"     Filename {track.filename}")
        out.append("")
    if track.peak_level is not None:
        out.append(f"     Peak level {track.peak_level * 100:.1f} %")
    if track.extraction_speed is not None:
        out.append(f"     Extraction speed {track.extraction_speed:.1f} X")
    if track.extraction_quality is not None:
        out.append(f"     Track quality {track.extraction_quality:.1f} %")
    if track.test_crc:
        out.append(f"     Test CRC {track.test_crc.upper()}")
    if track.copy_crc:
        out.append(f"     Copy CRC {track.copy_crc.upper()}")
    out.append(f"     {_accuraterip_line(track)}")
    if track.status:
        out.append(f"     {_status_line(track.status)}")
    out.append("")
    return out


def _accuraterip_line(track: TrackResult) -> str:
    """EAC-style AccurateRip verdict for a track, from real data only.

    Uses the shared ``accuraterip_is_match`` (confidence >= 1) so this agrees
    with the UI's verdict banner and disc-info panel — one definition of
    "verified" everywhere. Prefers the v2 result (EAC's own preference).
    """
    for ar in (track.accuraterip_v2, track.accuraterip_v1):
        if accuraterip_is_match(ar):
            assert isinstance(ar, AccurateRipResult)
            crc = f"  [{ar.local_crc}]" if ar.local_crc else ""
            return f"Accurately ripped (confidence {ar.confidence}){crc}  (AR v{ar.version})"
    return "Track not present in AccurateRip database"


def _status_line(status: str) -> str:
    """Render the track status the way EAC does for a clean copy."""
    # EAC writes "Copy OK"; our backends use phrases like "ripped successfully".
    normalized = status.strip().lower()
    if normalized in ("copy ok", "ripped successfully"):
        return "Copy OK"
    return status.strip()


def _yes_no(value: bool | None) -> str:
    """EAC writes Yes/No; an unknown (None) renders as a neutral marker."""
    if value is None:
        return "(unknown)"
    return "Yes" if value else "No"
