"""Render a parsed :class:`RipLog` into an EAC-*layout* text log.

**This is NOT a genuine EAC log and it is never signed as one.** See
``docs/eac-log-and-repair-feasibility.md``: EAC's ``==== Log checksum <hex> ====``
footer is an attestation that *Exact Audio Copy* produced the rip, so emitting
that exact marker over our (cyanrip) output would be **forging provenance** — a
bannable "faked log" on gazelle trackers and a direct violation of the project's
"never fake a log/checksum" rule. We never emit EAC's marker.

What this *does* produce is an honest, conspicuously-attributed log that mirrors
EAC's section/per-track layout so a human can ``diff``/``meld`` it against a real
EAC log and see the per-track Copy CRCs line up — the readable companion to the
programmatic ``scripts/eac_parity.py`` check. Honesty guardrails enforced here:

* The very first line says it was generated by Platterpus and is **not** a
  genuine EAC log — visible at first glance and in any ``head``.
* No fake ``Exact Audio Copy Vx.y`` version banner and **no**
  ``==== Log checksum <hex> ====`` line (EAC's exact marker); the log carries an
  explicit "not signed by Exact Audio Copy" disclaimer where EAC's marker sits.
* Only real data from the rip is rendered — absent fields are omitted, never
  invented.

**Log integrity checksum (KDD-28).** In addition to the disclaimer, the log ends
with a Platterpus integrity checksum: a **plain SHA-256 of the log text above it**,
clearly labelled *not an EAC checksum*. This is an *equal-or-stronger, honestly
attributed* analogue of EAC's tamper-evidence footer, not a copy of it: EAC's
checksum is a SHA-256 obfuscated with a fixed (reverse-engineered) key so only an
EAC "Logchecker" can verify it, whereas ours uses the same hash primitive
*openly* — anyone can reproduce it with a standard tool and no secret
(``head -n -1 "<name> (EAC-compatible).log" | sha256sum`` yields the same hex).
Same cryptographic strength, more transparent to verify, and never mistaken for
EAC's own signature. :func:`verify_eac_style_log_checksum` re-checks a rendered
log in-process.

The output is still *detected as EAC-format* by our own parser
(``parsers/eac_log.looks_like_eac_log`` keys on the ``Exact Audio Copy`` banner
prefix, which "Exact Audio Copy-compatible…" satisfies), so the parity tooling
can read the Copy CRCs straight back out of it.

Like the parsers, this never raises on a partially-populated ``RipLog``.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import re

from platterpus.parsers.rip_log import (
    AccurateRipResult,
    RipLog,
    TrackResult,
    accuraterip_is_match,
)

log = logging.getLogger(__name__)

# The first line. It MUST start with "Exact Audio Copy" so our own EAC parser
# detects the format (the banner regex is `^Exact Audio Copy\b`, and the "-"
# after "Copy" is a word boundary), while making it unmistakable to a human
# that this was generated by us and is not a real EAC log.
_BANNER: str = "Exact Audio Copy-compatible log generated by Platterpus"

# Stands where EAC prints `==== Log checksum <hex> ====`. Its presence is the
# honest tell that this log was not signed by EAC. (We DO still append our own
# integrity checksum below it — see `_CHECKSUM_PREFIX` — but that line names
# itself as ours, never as EAC's.)
_NOT_SIGNED: str = (
    "==== This log was generated by Platterpus and is NOT signed by "
    "Exact Audio Copy ===="
)

# The Platterpus integrity checksum footer (KDD-28). It is deliberately worded
# NOT to match EAC's `==== Log checksum <hex> ====` marker — it starts with
# "Platterpus" and names SHA-256 + "not an EAC checksum" so it can never be read
# as EAC's signature. The hex is a plain (un-obfuscated) SHA-256 of every byte
# ABOVE this line, so anyone can reproduce it with a standard tool and no secret:
#   head -n -1 "<name> (EAC-compatible).log" | sha256sum
_CHECKSUM_PREFIX: str = "==== Platterpus log checksum "
# lowercase 64-hex, matching `sha256sum` output exactly so manual verification
# is a byte-for-byte string compare.
_CHECKSUM_HEX_RE: re.Pattern[str] = re.compile(r"\b([0-9a-f]{64})\b")


def _log_checksum(body: str) -> str:
    """Plain SHA-256 (lowercase hex) of the log text that precedes the footer.

    Openly verifiable: the same bytes fed to any SHA-256 tool give this hex.
    """
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def _checksum_footer(body: str) -> str:
    """The self-describing, not-EAC checksum line for a finished log ``body``."""
    return (
        f"{_CHECKSUM_PREFIX}(SHA-256 of the text above; NOT an EAC checksum): "
        f"{_log_checksum(body)} ===="
    )


def _finalize(body: str) -> str:
    """Append the integrity-checksum footer to a rendered ``body`` (ends in \\n).

    Kept in one place so every return path — the normal render and the
    exception fallback — produces a log that :func:`verify_eac_style_log_checksum`
    can validate.
    """
    return body + _checksum_footer(body) + "\n"


def verify_eac_style_log_checksum(full_text: str) -> bool | None:
    """Re-check the integrity checksum of a log produced by this module.

    Returns ``True`` if the footer's SHA-256 matches the text above it, ``False``
    if the log was altered after rendering, and ``None`` if no Platterpus
    checksum footer is present (e.g. a real EAC log, or older output). Never
    raises — a malformed input yields ``None`` rather than an exception, matching
    the never-raises discipline of the renderer and parsers.
    """
    try:
        lines = full_text.splitlines(keepends=True)
        for i in range(len(lines) - 1, -1, -1):
            if lines[i].startswith(_CHECKSUM_PREFIX):
                match = _CHECKSUM_HEX_RE.search(lines[i])
                if match is None:
                    return None
                body = "".join(lines[:i])
                # constant-time compare — this is an integrity check, and a
                # timing-safe compare costs nothing and models the intent.
                return hmac.compare_digest(match.group(1), _log_checksum(body))
        return None
    except Exception:  # noqa: BLE001 — a verifier must never crash a caller
        log.exception("EAC-style log checksum verification failed")
        return None


def render_eac_style_log(
    rip_log: RipLog,
    *,
    platterpus_version: str = "",
    build_fingerprint: str = "",
    encoder_versions: dict[str, str] | None = None,
) -> str:
    """Return an EAC-layout, clearly-attributed text rendering of ``rip_log``.

    Optional provenance (keyword-only, defaulted so old callers/tests are
    unaffected) is recorded in the attribution header so the archival text
    artifact carries *which softwares produced it*:

    * ``platterpus_version`` / ``build_fingerprint`` — this app's own version
      and build (the log previously named "Platterpus" with no version).
    * ``encoder_versions`` — ``{dep_id: version}`` for the FLAC encoder
      (``flac``/``metaflac``) and, when a derived format was produced,
      ``ffmpeg``; from :func:`platterpus.build_info.encoder_versions`.

    The honesty gate still holds: any value not supplied is **omitted, never
    invented**, the cyanrip source line is left exactly as parsed, and EAC's own
    ``==== Log checksum <hex> ====`` marker is never added. The log *does* end
    with a Platterpus integrity checksum (a plain SHA-256 of the text above it,
    self-labelled *not an EAC checksum* — KDD-28); it is our own, openly
    verifiable, and never presented as EAC's.

    Never raises — a malformed/partial ``RipLog`` yields a best-effort log with
    a valid attribution header, disclaimer, and checksum footer (matching the
    never-raises discipline of the parsers this complements).
    """
    try:
        return _render(
            rip_log,
            platterpus_version=platterpus_version,
            build_fingerprint=build_fingerprint,
            encoder_versions=encoder_versions or {},
        )
    except Exception:  # noqa: BLE001 — a formatter must never crash a caller
        log.exception("EAC-style log render failed; emitting minimal stub")
        stub = (
            "\n".join([_BANNER, "", "(log could not be rendered)", "", _NOT_SIGNED])
            + "\n"
        )
        return _finalize(stub)


def _render(
    rip_log: RipLog,
    *,
    platterpus_version: str,
    build_fingerprint: str,
    encoder_versions: dict[str, str],
) -> str:
    info = rip_log.ripping_info
    source = rip_log.log_creator or "an unknown backend"
    # Attribution header. Software provenance lines are appended only for values
    # actually supplied (the "never invent a log line" rule) and sit between the
    # cyanrip source line and the not-an-EAC-log disclaimer.
    lines: list[str] = [
        _BANNER,
        f"  Rendered from a rip by {source}.",
    ]
    lines.extend(
        _provenance_lines(platterpus_version, build_fingerprint, encoder_versions)
    )
    lines.extend(
        [
            "  This is NOT a genuine EAC log, carries no EAC log checksum, and must",
            "  not be presented as an EAC rip. It mirrors EAC's layout only so the",
            "  per-track Copy CRCs can be compared against a real EAC log.",
            "",
        ]
    )
    if rip_log.creation_date:
        lines.append(f"Rip date : {rip_log.creation_date}")
        lines.append("")

    # --- Drive / read settings (EAC's archival block) ---
    if info.drive:
        lines.append(f"Used drive  : {info.drive}")
        lines.append("")
    # NB: "Read mode" and "Make use of C2 pointers" are deliberately NOT
    # emitted. EAC prints them, but our RippingInfo has no field behind them —
    # cyanrip doesn't report either — so hardcoding "Secure" / "No" would be
    # inventing rip facts (the same "never invent a log line" rule the banner
    # states). We render only fields we actually parsed; "Defeat audio cache"
    # renders "(unknown)" when unreported rather than a fabricated value (#32).
    lines.append(f"Defeat audio cache      : {_yes_no(info.defeat_audio_cache)}")
    lines.append("")
    if info.read_offset_correction is not None:
        lines.append(
            f"Read offset correction                      : "
            f"{info.read_offset_correction}"
        )
    lines.append(
        f"Overread into Lead-In and Lead-Out          : {_yes_no(info.overread_lead_out)}"
    )
    if info.gap_detection:
        lines.append(
            f"Gap handling                                : {info.gap_detection}"
        )
    lines.append("")

    # --- Per-track blocks ---
    for track in rip_log.tracks:
        lines.extend(_track_block(track))

    # --- Conclusive report ---
    lines.append("")
    if rip_log.accuraterip_summary:
        lines.append(f"AccurateRip summary : {rip_log.accuraterip_summary}")
    if rip_log.health_status:
        lines.append(f"Health status       : {rip_log.health_status}")
    lines.append("")
    # Deliberately NOT a real "==== Log checksum <hex> ====": that is EAC's
    # signature, and signing our output as EAC would be forgery.
    lines.append(_NOT_SIGNED)
    body = "\n".join(lines) + "\n"
    # …then append OUR own openly-verifiable integrity checksum (KDD-28): a plain
    # SHA-256 of everything above it, named as Platterpus's (never EAC's). Equal
    # hash strength to EAC's log checksum, but verifiable with a standard tool and
    # no secret key.
    return _finalize(body)


def _provenance_lines(
    platterpus_version: str,
    build_fingerprint: str,
    encoder_versions: dict[str, str],
) -> list[str]:
    """Software-provenance header lines — only for values actually supplied.

    Records *which softwares produced this rip* (beyond the cyanrip source line,
    which the caller renders separately from the parsed log): Platterpus's own
    version+build and the FLAC / derived-format encoder versions. An absent
    value produces no line — we never invent a version we didn't measure.
    """
    out: list[str] = []
    if platterpus_version:
        build = f" (build {build_fingerprint})" if build_fingerprint else ""
        out.append(f"  Generated by Platterpus {platterpus_version}{build}.")
    # The lossless master's encoder (flac + metaflac tag pass).
    flac_parts = [
        f"{name} {encoder_versions[name]}"
        for name in ("flac", "metaflac")
        if encoder_versions.get(name)
    ]
    if flac_parts:
        out.append(f"  FLAC encoder: {', '.join(flac_parts)}.")
    # ffmpeg only appears when a derived (mp3/wavpack/wav) format was produced.
    if encoder_versions.get("ffmpeg"):
        out.append(f"  Derived-format encoder: ffmpeg {encoder_versions['ffmpeg']}.")
    return out


def _track_block(track: TrackResult) -> list[str]:
    """The per-track section, matching EAC's shape (only real fields rendered)."""
    out: list[str] = [f"Track  {track.number}", ""]
    if track.filename:
        out.append(f"     Filename {track.filename}")
        out.append("")
    if track.peak_level is not None:
        out.append(f"     Peak level {track.peak_level * 100:.1f} %")
    if track.extraction_speed is not None:
        out.append(f"     Extraction speed {track.extraction_speed:.1f} X")
    if track.extraction_quality is not None:
        out.append(f"     Track quality {track.extraction_quality:.1f} %")
    out.extend(_crc_lines(track))
    out.append(f"     {_accuraterip_line(track)}")
    if track.status:
        out.append(f"     {_status_line(track.status)}")
    out.append("")
    return out


def _crc_lines(track: TrackResult) -> list[str]:
    """The per-track CRC lines, in EAC's Test/Copy shape when we earned it.

    EAC's secure mode prints a **Test CRC** and a **Copy CRC** — two full read
    passes whose match is the proof the extraction is reproducible. cyanrip's
    equivalent is ``-Z N`` (re-rip a track until N reads' checksums agree): a
    track that *converged* was read at least twice and produced the identical
    CRC each time — the same two-reads-agree guarantee, by a cheaper mechanism.

    So when a track was verified by ≥2 agreeing reads we render the CRC as an
    EAC-style **Test CRC == Copy CRC** pair (they are provably equal — that IS
    what convergence means) plus an honest note naming how it was confirmed. A
    single-read track (``-Z`` off, or a clean track on the dynamic fast path)
    gets only a Copy CRC — we never fabricate a second "test" read that didn't
    happen. A backend that natively reports a distinct ``test_crc`` (whipper's
    dual read) is rendered as-is.
    """
    out: list[str] = []
    # Native dual-read backend (whipper): show whatever it actually reported.
    if track.test_crc:
        out.append(f"     Test CRC {track.test_crc.upper()}")
        if track.copy_crc:
            out.append(f"     Copy CRC {track.copy_crc.upper()}")
        return out
    if not track.copy_crc:
        return out
    crc = track.copy_crc.upper()
    reads = track.rip_count if track.rip_count and track.rip_count >= 1 else 1
    verified = track.secure_rerip_converged is True or reads >= 2
    if verified:
        # ≥2 reads agreed → the CRC is both the test-read's and the copy-read's
        # result. Render the EAC Test/Copy pair + an honest provenance note.
        note = (
            f"  (Test and Copy CRC identical — confirmed across {reads} secure "
            "re-reads)"
            if reads >= 2
            else "  (Test and Copy CRC identical — reads converged)"
        )
        out.append(f"     Test CRC {crc}")
        out.append(f"     Copy CRC {crc}{note}")
    else:
        out.append(f"     Copy CRC {crc}")
    return out


def _accuraterip_line(track: TrackResult) -> str:
    """EAC-style AccurateRip verdict for a track, from real data only.

    Uses the shared ``accuraterip_is_match`` (confidence >= 1) so this agrees
    with the UI's verdict banner and disc-info panel — one definition of
    "verified" everywhere. Prefers the v2 result (EAC's own preference).
    """
    for ar in (track.accuraterip_v2, track.accuraterip_v1):
        if accuraterip_is_match(ar):
            assert isinstance(ar, AccurateRipResult)
            crc = f"  [{ar.local_crc}]" if ar.local_crc else ""
            return f"Accurately ripped (confidence {ar.confidence}){crc}  (AR v{ar.version})"
    # No exact match — but cyanrip may still have matched the **+450 offset-variant
    # pressing**, in which case the track IS in AccurateRip and "not present" would
    # be factually FALSE. Real-hardware bug (2026-07-26, tracks 3 & 5 of the Police
    # "Classics" rip): cyanrip logged "Accurip 450: … matches Accurip DB, confidence
    # 200" and our own verdict banner said "matched an offset-variant pressing", yet
    # this log claimed the tracks weren't in the database at all — three surfaces
    # disagreeing about the same parsed RipLog.
    #
    # Reuse the project's ONE wording for this state ("offset-variant … partially
    # accurate", as in verdict.py and the results table) so no surface invents its
    # own phrasing. It never claims a plain match — offset-variant is deliberately
    # NOT "verified" (see accuraterip_is_match's callers and KDD-27).
    offset_variant = track.accuraterip_offset
    if accuraterip_is_match(offset_variant):
        assert isinstance(offset_variant, AccurateRipResult)
        crc = f"  [{offset_variant.local_crc}]" if offset_variant.local_crc else ""
        return (
            "Matched an offset-variant pressing — partially accurate "
            f"(confidence {offset_variant.confidence}){crc}  (AR +450)"
        )
    return "Track not present in AccurateRip database"


def _status_line(status: str) -> str:
    """Render the track status the way EAC does for a clean copy."""
    # EAC writes "Copy OK"; our backends use phrases like "ripped successfully".
    normalized = status.strip().lower()
    if normalized in ("copy ok", "ripped successfully"):
        return "Copy OK"
    return status.strip()


def _yes_no(value: bool | None) -> str:
    """EAC writes Yes/No; an unknown (None) renders as a neutral marker."""
    if value is None:
        return "(unknown)"
    return "Yes" if value else "No"
