"""Parse Exact Audio Copy (EAC) rip logs — the per-track Copy CRCs.

EAC is the bit-perfect baseline this project measures against (see
``output_reference/`` and ``docs/test-plan.md``). Its log format differs from
the legacy YAML-ish log format and from cyanrip's report, so it needs its own reader.
Parity only needs each track's **Copy CRC**, so this is intentionally minimal
rather than a full EAC parser.

EAC track-block shape (verified against the committed baseline
``output_reference/EAC_flac/eac_baseline_police_classics.log``)::

    Track  1

         Filename D:\\My Music\\01 - Roxanne - The Police.wav
         Peak level 94.2 %
         Test CRC B0D122E7
         Copy CRC B0D122E7

**Two programs write this layout, and the first line says which.** A genuine
EAC log opens with EAC's own banner. Platterpus's EAC-compatible export
(``eac_log_export.py``) opens with a line of its own that begins "Platterpus".
Both carry the same per-track blocks, so the Copy CRCs read out of either the
same way, and :func:`eac_log_producer` reports which program the first line
names. Our export used to begin "Exact Audio Copy-compatible…", which a
first-words check (ours included) filed as EAC's own log. That wording is still
recognised, as ours, because users and committed artifacts hold logs that carry it.

Like every parser of external output, this must never raise on arbitrary text —
it degrades to an empty mapping (institutional rule, ``docs/testing.md``).
"""

from __future__ import annotations

import re
from typing import Final, Literal

from platterpus.safe_int import int_or_none

#: Which program wrote an EAC-layout log, as its first line states it. This is
#: what the log SAYS, not proof: EAC's banner is plain text anyone can type, and
#: only EAC's own log checksum (which nothing here checks) attests that EAC made
#: a file. :func:`eac_log_producer` returns `None` for text in neither layout.
EacLogProducer = Literal["exact_audio_copy", "platterpus"]

# "Exact Audio Copy V1.8 from ..." — the first line of any EAC log (often
# preceded by a UTF-8 BOM, which we strip before matching). Deliberately loose
# (no version number required) so a hand-trimmed baseline still reads. The
# Platterpus banners below are checked FIRST, because the old one begins this way.
_EAC_BANNER = re.compile(r"^Exact Audio Copy\b", re.IGNORECASE)

#: The first line of Platterpus's own EAC-layout export, in every wording it has
#: had, newest first. `eac_log_export._BANNER` writes the first entry, and a test
#: renders a log and holds the writer and this table to agreeing. Each is matched
#: as a case-insensitive prefix of the first non-blank line. Never remove one: a
#: wording that leaves this table turns every log written with it into "not an
#: EAC-layout log" (the new wording) or "written by EAC" (the old one).
PLATTERPUS_EAC_BANNERS: Final[tuple[str, ...]] = (
    # Written by the releases after 0.6.62. It begins with "Platterpus" so no tool
    # which sniffs a log's format from its first words, as ours did, files it as
    # a log EAC wrote (handshake round 28 lap 7 S28-S32, accepted by the cyanrip
    # fork in round 29 lap 1 S31).
    "Platterpus rip log in EAC's layout, not produced by Exact Audio Copy",
    # Written by Platterpus 0.6.62 and earlier. It begins with "Exact Audio Copy",
    # so without this entry `_EAC_BANNER` would name it EAC's own log: on files
    # already written, the misfiling the new wording was chosen to end.
    "Exact Audio Copy-compatible log generated by Platterpus",
)

# A per-track block opens with "Track  N" at column 0 (EAC pads the number with
# spaces). Distinct from the TOC table rows, which are indented and pipe-delimited.
_TRACK_HEADER = re.compile(r"^Track\s+(?P<number>\d+)\s*$")
# "     Copy CRC B0D122E7" — 8 hex digits, space-separated (no colon, unlike
# the legacy log format's "Copy CRC: ...").
_COPY_CRC = re.compile(r"^\s*Copy CRC\s+(?P<crc>[0-9A-Fa-f]{8})\b")


def eac_log_producer(text: str) -> EacLogProducer | None:
    """Which program's EAC-layout log `text` is, read from its first non-blank line.

    ``"platterpus"`` when that line begins with one of our export's banners (either
    wording), ``"exact_audio_copy"`` when it begins with EAC's banner, and ``None``
    for anything else. Ours is tested first: the banner Platterpus 0.6.62 and
    earlier wrote also begins "Exact Audio Copy". A leading UTF-8 BOM is ignored,
    as EAC's UTF-16 logs often carry one. Never raises.
    """
    for line in text.splitlines():
        if not line.strip():
            continue  # EAC-layout logs may open with blank lines
        first = line.lstrip("\ufeff")
        folded = first.casefold()
        if any(
            folded.startswith(banner.casefold()) for banner in PLATTERPUS_EAC_BANNERS
        ):
            return "platterpus"
        if _EAC_BANNER.match(first):
            return "exact_audio_copy"
        return None  # only the first non-blank line names the producer
    return None


def looks_like_eac_log(text: str) -> bool:
    """True if `text` is in EAC's log layout: EAC's own log, or our export of it.

    Both carry the per-track ``Copy CRC`` rows the parity tooling reads, so every
    caller that picks a parser by format wants both. :func:`eac_log_producer`
    tells them apart.
    """
    return eac_log_producer(text) is not None


def parse_eac_copy_crcs(text: str) -> dict[int, str]:
    """Return ``{track_number: uppercase Copy CRC}`` from an EAC log.

    Only the Copy CRC is extracted — that's what bit-perfect parity compares.
    Tolerates absent fields and unexpected lines; never raises.
    """
    crcs: dict[int, str] = {}
    current: int | None = None
    for line in text.splitlines():
        header = _TRACK_HEADER.match(line)
        if header:
            # An unusable number closes the previous track rather than keeping it
            # open: the CRC rows that follow belong to whatever this header names,
            # so attributing them to the *last* good track number would file one
            # track's checksum under another's — a wrong parity verdict, which is
            # worse than a missing one.
            current = int_or_none(header.group("number"), field="EAC track number")
            continue
        crc = _COPY_CRC.match(line)
        if crc and current is not None:
            crcs[current] = crc.group("crc").upper()
    return crcs
