#!/usr/bin/env python3
"""Emit Platterpus's half of the cyanrip dependency contract, derived from code.

Platterpus and the cyanrip fork are each other's dependency: we consume cyanrip's
log and argv surface, and the fork's log format exists to satisfy us. A handshake
(``docs/cyanrip-handshake.md``) is only checkable if each side can state its half
of that seam *precisely* — and a hand-maintained statement drifts from the code
the week after it is written.

So this script does not restate anything. It **imports the parser and the backend
adapter and asks them**:

* every log line we recognise comes from the parser's own enumeration tables
  (the same tables ``tests/test_parsers_cyanrip_log.py`` already asserts are a
  complete listing of the module's patterns);
* every line we knowingly ignore comes from ``_IGNORED_DISC_LINES``, with the
  written reason attached;
* every flag we pass comes from calling the real ``_build_rip_argv`` with a
  maximal parameter set, so a flag that stops being emitted disappears from the
  contract on the next run.

``tests/test_dependency_contract_emitted.py`` regenerates this and diffs it
against the committed ``docs/cyanrip-consumer-contract.md``, so the file cannot
go stale without CI going red.

Usage::

    python scripts/emit_dependency_contract.py            # write the doc
    python scripts/emit_dependency_contract.py --stdout   # print, write nothing
    python scripts/emit_dependency_contract.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "src"))

from platterpus import __version__ as _APP_VERSION  # noqa: E402
from platterpus.adapters.cyanrip_backend import CyanripImpl  # noqa: E402
from platterpus.adapters.rip_backend import RipMetadata, TrackTag  # noqa: E402
from platterpus.cyanrip_cli import (  # noqa: E402
    VERIFY_LOG_FLAG,
    VERSION_FLAGS,
)
from platterpus.deps.fork_source import (  # noqa: E402
    FORK_EXPECTED_BANNER as _APPROVED_BANNER,
)
from platterpus.handshake_approval import (  # noqa: E402
    APPROVED_BY_ROUND as _APPROVED_ROUND,
)
from platterpus.handshake_approval import (  # noqa: E402
    APPROVED_FOR_PLATTERPUS_VERSION as _APPROVED_FOR,
)
from platterpus.parsers import cyanrip_log as _parser  # noqa: E402
from platterpus.rig_check import DIAGNOSTICS_FLAG  # noqa: E402

OUTPUT_PATH: Path = _REPO_ROOT / "docs" / "cyanrip-consumer-contract.md"

# A marker so the fork's tooling (and a human) can tell at a glance that editing
# the file by hand is pointless.
_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/emit_dependency_contract.py — do not edit by "
    "hand; edit the parser/adapter and regenerate. -->"
)

# Rows whose regex only ever matches output the fork emits. Marked so the fork
# knows which lines it is on the hook for, and so an upstream cyanrip release
# that adopts one can be spotted.
#
# **HAND-MAINTAINED, WHICH MAKES IT THE WEAK JOINT IN A GENERATED DOCUMENT.**
# Everything else on this page is derived; this set is typed, so it goes stale
# silently and in the direction that *understates* the fork's obligation. It did:
# the four `album_*` rules landed on 2026-08-21 and this set was not extended, so
# the contract we publish said "9 exist only in the fork" when it was 13 — for
# exactly the four rows we had just made ourselves depend on. The fork could have
# reworded them believing nothing consumed them, which is the failure this whole
# document exists to prevent, arriving through the one field the document does not
# derive.
#
# Adding a rule that parses fork-only output? Add it here in the same commit.
# `tests/test_dependency_contract_emitted.py` holds the count against the rules
# whose patterns mention a fork-only label, so the omission now fails rather than
# publishing a smaller number.
_FORK_ONLY_RULES: frozenset[str] = frozenset(
    {
        "track_pregap_length",
        "track_pregap_source",
        "track_peak_kind_header",
        "track_sample_peak",
        "track_extraction_speed",
        "track_elapsed_seconds",
        "track_secure_verdict",
        "track_accurip_status",
        # The four whole-disc rows the fork declares in P2 as its own API, added
        # 2026-08-21. We now read these IN PREFERENCE to FFmpeg's `ebur128`
        # block, which the fork's P3 disclaims as libavfilter's wording — so
        # these four are the ones where a silent reword costs us the values
        # outright rather than degrading to a fallback.
        "album_integrated_loudness",
        "album_loudness_range",
        "album_sample_peak_level",
        "album_true_peak_level",
        # The six the fork CONFIRMED as theirs on 2026-08-21, answering our round-12
        # lap 4 §C1. They did not answer from a sample of logs (which is all we can
        # do) — `tools/upstream-delta.py` diffs every `cyanrip_log()` format string
        # in their tree against their verbatim mirror of `cyanreg/cyanrip` at
        # 0.9.4-rc2, so the claim is *"upstream's source does not print this"*
        # rather than *"we have not seen it in six stock logs"*. Each also has a
        # row in their published P2 inventory naming the emitting `file:line`,
        # which is the half we can check in-house and
        # `tests/test_provider_contract_agreement.py` now does.
        #
        # `rip_completed` was the surprise, and in the *safe* direction: we had it
        # recorded as "the fork owns the wording, not the line" because their §D1
        # reworded it. Measured, upstream prints no `Rip completed:` line at all —
        # they own both. An uncertainty resolved in favour of MORE fork obligation
        # is the one worth noticing, because the default drift is the other way.
        "consumer",
        "handshake_note",
        "invoked_as",
        "read_stalls",
        # Added by the fork in round 13 to answer our round-12 ask: which track
        # was in progress when a rip was interrupted. Fork-only by construction
        # — upstream has no such line — and published here so they know they
        # are on the hook for it.
        "interrupted_at",
        # Their round-13 lap-3 fix for the over-reporting we reported in the same
        # round: a `Scope:` note inside the per-track paranoia block saying which
        # reads the numbers cover. Fork-only, and published here because it is a
        # line we now depend on being a block MEMBER rather than a terminator.
        "track_paranoia_scope",
        "secure_rerip_converged",
        "rip_completed",
    }
)

# Rules whose regex matches text **PLATTERPUS ITSELF WRITES**, not text cyanrip
# emits. Excluded from §1 and published in their own section instead.
#
# **Why this category has to exist, and why it is the most useful thing the fork
# found in round 12.** `swap_addendum_crc` parses the `[Platterpus auto-fix
# addendum]` block — our own text, written by
# `src/platterpus/rip_addendum.py:render_addendum`. It was sitting in §1, a table
# headed *"Log lines we parse"* inside a document whose entire purpose is to tell
# the fork what we depend on **them** for, under the sentence *"any change to a
# line in §1 is a breaking change to us and requires a handshake round."* That is
# a false claim in the worst available direction: it asks another project to hold
# a line stable that it does not emit and cannot break.
#
# The fork settled it from their tree rather than from belief: the string
# `addendum` appears **zero** times in their `src/` and zero times in upstream's.
# Our own corroboration is stronger still — the one committed "fork log" the rule
# matches is `output_reference/cyanrip_fork_flac/cyanrip_fork_police_classics.log`,
# where the match at line 1150 sits *inside* our own addendum block opened at line
# 1145. So the log-corpus derivation that flagged it as fork-only was reading our
# own output back and calling it theirs.
#
# **The rule STAYS in the parser** — this is a publication fix, not a deletion.
# `rip_addendum.with_addendum` deliberately concatenates the sidecar onto the
# ripper's log and hands the combined text to `parse_cyanrip_log`, so that parser
# is the parser of the *augmented* log. Dropping the rule would resurrect the
# 2026-07-28 defect where a re-parse from disk reported the CRCs of the read we
# discarded (`tests/test_auto_fix_convergence.py`
# ::test_a_saved_log_reparses_to_the_shipped_crcs_not_the_discarded_ones).
#
# Membership is CHECKED, not asserted: the test renders a real addendum with
# `rip_addendum.render_addendum` and requires each name here to match a line of
# it, so this set is derived from our own emitter rather than typed. Note
# `track_secure_verdict` deliberately does **not** belong here — the addendum
# mirrors cyanrip's own `Secure re-read:` label so the supersede is read, and the
# fork really does emit that line (their P2, `cyanrip_log.c:441/444/449`).
_OUR_OWN_OUTPUT_RULES: frozenset[str] = frozenset({"swap_addendum_crc"})


def _escape_cell(text: str) -> str:
    """Make a regex safe to drop into a Markdown table cell."""
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def _pattern_rows() -> list[tuple[str, str, str]]:
    """(name, regex, scope) for every log line the parser recognises.

    Sourced from the three enumeration tables the parser already maintains, so
    a pattern added to the module without being listed shows up here the moment
    the existing completeness test forces it into a table.
    """
    rows: list[tuple[str, str, str]] = []
    for rule in _parser._ALL_LINE_RULES:
        rows.append((rule.name, rule.pattern.pattern, "disc"))
    for name, pattern in _parser._SECTION_LINE_PATTERNS:
        rows.append((name, pattern.pattern, "section header"))
    for name, pattern in _parser._INDENTED_LINE_PATTERNS:
        rows.append((name, pattern.pattern, "indented"))
    return rows


def _ignored_rows() -> list[tuple[str, str]]:
    """(regex, written reason) for lines we deliberately do not parse."""
    return [
        (pattern.pattern, reason) for pattern, reason in _parser._IGNORED_DISC_LINES
    ]


def _emitted_flags() -> list[str]:
    """Every flag we can hand cyanrip, obtained by *calling* the arg builder.

    A maximal parameter set is used so conditional flags (``-Z``, ``-O``, ``-S``,
    ``-l``, ``-G``) are all present. This is a derivation, not a list: a flag the
    adapter stops passing vanishes from the contract, and one it starts passing
    appears, without anyone remembering to edit a doc.
    """
    backend = CyanripImpl(binary_path="cyanrip")
    argv = backend._build_rip_argv(
        "/dev/sr0",
        unknown=False,
        cover_art="",  # falsy -> emits -G, so the flag appears in the contract
        max_retries=8,
        read_offset_override=667,
        release_id="00000000-0000-0000-0000-000000000000",
        track_template="%A/%d/%t %n",
        # Real metadata, so the per-track `-t` flag is exercised too. With
        # `metadata=None` only the album-level `-a` appears and the contract
        # would understate the argv we actually send.
        metadata=RipMetadata(
            album_artist="Artist",
            album_title="Album",
            year="1986",
            tracks=(TrackTag(number=1, title="Track"),),
        ),
        secure_rerip_matches=2,
        force_overread=True,
        read_speed=8,
        only_tracks=(1, 2),
        disc_track_total=14,
    )
    # argv[0] is the binary path, not a flag.
    #
    # SHORT **AND LONG** options. Short-only was the filter here, which made this
    # document — whose entire purpose is "this is what we send you" — under-report
    # our own argv the moment we added `--consumer`. The fork would have read a
    # contract that omitted a flag we actually send, which is worse than no
    # contract: it is a wrong one, published, generated, and therefore trusted.
    #
    # Third instance of this exact blind spot in one session (the rip audit's argv
    # comparison, the release gate's, and here). A pattern matching only `-X` looks
    # complete because every cyanrip flag *was* short.
    tokens = set(argv[1:])
    # The rip is not the only thing we run. Every invocation we make is part of the
    # argv surface, and a renamed flag is indistinguishable from an absent tool —
    # which is exactly how upstream's `-V` removal turned a working fork build into
    # "cyanrip is not installed". So the probes are enumerated here too, from the
    # same constants the code uses, rather than left out because they are not a rip.
    #
    # Added when `--verify-log` became a third invocation shape (round 7 lap 10,
    # J3): the version probe had already taught this lesson and this document still
    # described only the rip.
    tokens.update(VERSION_FLAGS)
    tokens.add(VERIFY_LOG_FLAG)
    # FOURTH invocation shape: the rig-check argv probe, which runs the binary with
    # `-j` to read its own command line back out of the diagnostics record.
    #
    # It was missing, so this document — headed "Flags we pass you" and therefore
    # read as complete — listed 18 and omitted one we really send. The comment
    # directly above already said every invocation we make belongs here; the
    # population it was written over did not include this one, which is the same
    # "scoping a sweep silently while the rule claims everything" defect the
    # comment above records two earlier instances of. Third time in this function.
    #
    # Found 2026-08-21 while checking a cyanrip round-12 claim about the `-j`
    # record's schema — a claim that was itself possible partly because neither
    # side's published contract described this surface at all.
    tokens.add(DIAGNOSTICS_FLAG)
    return sorted(
        {
            token
            for token in tokens
            if re.fullmatch(r"-[A-Za-z]", token)
            or re.fullmatch(r"--[A-Za-z][\w-]*", token)
        }
    )


def render() -> str:
    """Build the whole document. Deterministic — no timestamps.

    **No date, but it does name versions, and the change is deliberate.** The
    original reasoning was sound and is preserved in §0: a *timestamp* would make
    every unrelated release produce a spurious diff and train readers to ignore the
    ones that matter. A *version* is different — it is the range the claims cover,
    which round 7 lap 10 asked both sides to state (ask D3), because a contract
    claim with no stated range is a snapshot that reads as a fact. The fork's
    *"there is no `-V`"* was true when written and one commit from being the
    misleading kind of true.

    The cost is honest and accepted: this file now diffs by two lines on a version
    bump. That diff is not spurious — the document really does describe a new app
    version — and it is the price of a range a reader can check. **Do not "fix" it
    back to versionless**; that would re-open exactly the ambiguity D3 was raised
    about.

    Still deterministic for a given (source, version) pair, so `--check` remains a
    valid CI gate.
    """
    all_patterns = _pattern_rows()
    # SPLIT BEFORE COUNTING. §1 is read as "lines cyanrip emits that we depend
    # on", so a rule that parses our *own* text must not be counted there — the
    # number is the first thing anyone reads and it was one too high.
    patterns = [row for row in all_patterns if row[0] not in _OUR_OWN_OUTPUT_RULES]
    ours = [row for row in all_patterns if row[0] in _OUR_OWN_OUTPUT_RULES]
    ignored = _ignored_rows()
    flags = _emitted_flags()
    fork_only = [name for name, _, _ in patterns if name in _FORK_ONLY_RULES]

    lines: list[str] = [
        "# Platterpus → cyanrip: the consumer half of the contract",
        "",
        _GENERATED_BANNER,
        "",
        'This is the machine-derived answer to *"what does Platterpus actually',
        'depend on cyanrip emitting?"* — every row below is read out of the parser',
        "and the backend adapter at generation time, not written down beside them.",
        "",
        "It is one half of a pair. The other half is the fork's",
        "**provider contract** — what it guarantees to emit and what it needs from",
        "us — and neither half is a handshake on its own. See",
        "`docs/cyanrip-handshake.md` for the protocol both sides follow.",
        "",
        "**How to use it if you are the fork:** any change to a line in §1 is a",
        "breaking change to us and requires a handshake round. §1a is text **we**",
        "write, not you — it is listed so you can recognise it in an artifact we",
        "send you, and you owe nothing for it. Anything in §2 is safe to change",
        "freely — we look at it and throw it away. §3 is the argv we will send you;",
        "a flag whose meaning changes is also breaking.",
        "",
        # THE RANGE, NOT THE SNAPSHOT (round 7 lap 10, ask D3 — offered to the fork
        # and therefore owed by us).
        #
        # A contract claim with no stated range is a snapshot that reads as a fact.
        # The fork's *"`-v` is version; there is no `-V`"* was true when written and
        # one commit from being the misleading kind of true; our own dependency
        # dialog's `cyanrip 0.9.3 / 0 missing` had every word accurate and the
        # message wrong. Same shape, and the fix is the same: say WHICH BUILDS a
        # claim holds for.
        #
        # This document is generated from OUR code, so the honest range is the app
        # version that produced it and the ripper build it was verified against —
        # both of which we can state exactly rather than approximately, and neither
        # of which is a timestamp (the banner explains why there is no date).
        "## 0. What range these claims cover",
        "",
        "Every row in this document is derived from the Platterpus source at the",
        "version named below, and describes what **that** app version parses and",
        "sends. It is not a claim about any other version of either side.",
        "",
        f"- **Platterpus:** `{_APP_VERSION}` — the build that",
        "  generated this file. A row can only have changed with our code, so this",
        "  version *is* the range on our half.",
        f"- **Verified against ripper build:** `{_APPROVED_BANNER}` — the build a",
        f"  closed handshake round approved (round {_APPROVED_ROUND}, for Platterpus",
        f"  `{_APPROVED_FOR}`). Rows in §1 were checked against that build's output;",
        "  a newer ripper may emit lines this document does not list, which is a",
        "  handshake event rather than a defect.",
        "- **Ripper build under review:** see `HANDSHAKE-PIN` /",
        "  `HANDSHAKE-TEST-PIN` in the newest file under `docs/handshake/`. A test",
        "  pin is approved by nobody and this document makes no claim about it.",
        "",
        "*Why no date:* this file is a pure function of the code, so a timestamp",
        "would make every unrelated release produce a spurious diff and train",
        "readers to ignore the ones that matter. The versions above are the range;",
        "the git history is the chronology.",
        "",
        "---",
        "",
        f"## 1. Log lines we parse ({len(patterns)})",
        "",
        "Changing the text, indentation, or field order of any of these changes what",
        "Platterpus records about a rip. `scope` is where in the log the line is read:",
        "`disc` = a top-level row, `indented` = inside a section or track block,",
        "`section header` = a line that switches the parser's mode.",
        "",
        "| name | scope | pattern |",
        "|---|---|---|",
    ]
    for name, pattern, scope in patterns:
        mark = " **(fork-only)**" if name in _FORK_ONLY_RULES else ""
        lines.append(f"| `{name}`{mark} | {scope} | `{_escape_cell(pattern)}` |")

    lines += [
        "",
        f"Of these, **{len(fork_only)} exist only in the fork** and match nothing in",
        "stock cyanrip 0.9.3. They are the fork's specific obligation:",
        "",
    ]
    lines += [f"- `{name}`" for name in fork_only]

    # §1a — THE LINES THAT ARE OURS. See `_OUR_OWN_OUTPUT_RULES` for the full
    # reasoning; the short version is that publishing our own text in §1 asks
    # another project to keep a line stable that it does not emit.
    lines += [
        "",
        f"## 1a. Lines we parse that **we** write — not your obligation ({len(ours)})",
        "",
        "These match text **Platterpus** appends beside a rip, not anything cyanrip",
        'emits. They are listed here rather than in §1 because §1 means *"change',
        'this and you break us"*, which cannot be true of a line you do not print.',
        "You owe nothing for them, and you may see them in a rig log we send you:",
        "the block is what makes such a log fail `--verify-log`, which is expected",
        "and is why we now write it to a sidecar file instead of appending it to",
        "your log.",
        "",
        "| name | scope | written by | pattern |",
        "|---|---|---|---|",
    ]
    for name, pattern, scope in ours:
        lines.append(
            f"| `{name}` | {scope} | `src/platterpus/rip_addendum.py` "
            f"(`render_addendum`) | `{_escape_cell(pattern)}` |"
        )
    lines += [
        "",
        "Kept in the same parser on purpose: reading a rip's log back means reading",
        "the log **and** its addendum (`rip_addendum.with_addendum`), because the",
        "addendum is the only statement in the folder about which bytes actually",
        "shipped after an auto-fix re-rip.",
    ]

    lines += [
        "",
        f"## 2. Log lines we knowingly ignore ({len(ignored)})",
        "",
        "An allow-list, not a shrug — each entry is a recorded decision, and the",
        "parser's own test treats an unrecognised, unlisted line as a failure. So a",
        "row you add shows up as a red test on our side rather than being silently",
        "dropped.",
        "",
        "| pattern | why we ignore it |",
        "|---|---|",
    ]
    for pattern, reason in ignored:
        lines.append(f"| `{_escape_cell(pattern)}` | {reason} |")

    lines += [
        "",
        f"## 3. Flags we pass you ({len(flags)})",
        "",
        "Obtained by calling the real argv builder with a maximal parameter set, so",
        "this is what the adapter emits today rather than what it was documented to",
        "emit. Per-flag semantics and the exact contract for each are in",
        "`docs/dependency-contracts.md`.",
        "",
        "```",
        " ".join(flags),
        "```",
        "",
        "Two of these are load-bearing beyond their own behaviour:",
        "",
        "- **`-N` is always passed, unconditionally.** Platterpus is the single",
        "  metadata source (Critical rule #5); cyanrip must never perform its own",
        "  MusicBrainz lookup, because its interactive prompt would hang a GUI-driven",
        "  rip with no terminal attached.",
        "- **`-o flac` is always passed.** FLAC is the archival master; every other",
        "  output format Platterpus offers is transcoded from it host-side, so the",
        "  ripper is never asked for a lossy encode.",
        "",
        "## 4. What we need from you to close a handshake",
        "",
        "The return file's required sections are enumerated in",
        "`docs/cyanrip-handshake.md` §4. The short version: a commit SHA and exact",
        "`--version` string; measured-vs-read-from-source answers to every question;",
        'an explicit statement of whether the log format changed (**"no changes"**',
        "must be written out — silence is ambiguous); a regenerated golden log if it",
        "did; and your own provider contract, which is the mirror of this file.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--stdout", action="store_true", help="print instead of writing")
    group.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed file differs from the generated one",
    )
    args = parser.parse_args(argv)

    text = render()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        current = (
            OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        )
        if current == text:
            return 0
        sys.stderr.write(
            f"{OUTPUT_PATH.relative_to(_REPO_ROOT)} is stale.\n"
            "Regenerate with: python scripts/emit_dependency_contract.py\n"
        )
        return 1
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    sys.stdout.write(f"wrote {OUTPUT_PATH.relative_to(_REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
