#!/usr/bin/env python3
"""Write the README's *Getting started* section from the guide the app ships.

KDD-42 W6: the getting-started guide is **one source, two renderings**. The source
is ``src/platterpus/guide/getting-started.md``, inside the package so the app can
open it offline (Help → Getting started). The README carries the same guide for
people reading on GitHub, and a hand-kept copy there would drift the first time a
step changed. So the README's section is **generated**, the way
``docs/script-language.md`` and the dependency contract are, and
``tests/test_getting_started.py`` fails CI if the committed README and the guide
disagree.

The section sits between two marker comments in ``README.md``. Everything between
them is replaced; everything outside them is left exactly as it was. The guide's
text is changed in two ways only (see ``getting_started.readme_markdown``): its
headings move one level down under the README's own ``## Getting started``, and
its picture paths gain the guide folder's path so GitHub finds the same files the
app shows.

Usage::

    python scripts/emit_getting_started.py            # rewrite the README section
    python scripts/emit_getting_started.py --stdout   # print the section, write nothing
    python scripts/emit_getting_started.py --check    # exit 1 if the README is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Final

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from platterpus import getting_started  # noqa: E402 — after the path insert

README: Final[Path] = REPO_ROOT / "README.md"

BEGIN: Final[str] = (
    "<!-- getting-started:begin — generated by scripts/emit_getting_started.py "
    "from src/platterpus/guide/getting-started.md; edit that file, not this -->"
)
END: Final[str] = "<!-- getting-started:end -->"


def section() -> str:
    """The README's section: its title, the guide, between the two markers."""
    body = getting_started.readme_markdown(getting_started.guide_markdown())
    return f"{BEGIN}\n## Getting started\n\n{body}\n{END}"


def rendered_readme(readme_text: str) -> str | None:
    """``readme_text`` with its section replaced, or ``None`` if a marker is missing.

    Exactly one of each marker, BEGIN before END. Anything else is refused rather
    than guessed at, because a guess here rewrites the wrong part of the README.
    """
    if readme_text.count(BEGIN) != 1 or readme_text.count(END) != 1:
        return None
    start = readme_text.index(BEGIN)
    stop = readme_text.index(END)
    if stop < start:
        return None
    return readme_text[:start] + section() + readme_text[stop + len(END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="exit 1 if stale")
    group.add_argument("--stdout", action="store_true", help="print, write nothing")
    args = parser.parse_args(argv)

    if args.stdout:
        print(section())
        return 0
    current = README.read_text(encoding="utf-8")
    wanted = rendered_readme(current)
    if wanted is None:
        print(
            f"{README.name}: needs exactly one '{BEGIN[:30]}…' marker followed by "
            f"exactly one '{END}' marker",
            file=sys.stderr,
        )
        return 1
    if args.check:
        if wanted != current:
            print(
                f"{README.name}'s Getting started section is stale: run "
                "python3 scripts/emit_getting_started.py",
                file=sys.stderr,
            )
            return 1
        return 0
    if wanted != current:
        README.write_text(wanted, encoding="utf-8")
        print(f"wrote {README.name}'s Getting started section")
    else:
        print(f"{README.name}'s Getting started section is already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
